import {getState,subscribe,update} from './state.js';
import {observeVitals,observeErrors,track} from './analytics.js';
import {getSession,refreshEntitlement,paymentStatus,fetchWallet,releaseSha} from './api.js';
import {toast} from './ui.js';
import {renderHome,bindHome} from './views/home.js';
import {renderFeed,bindFeed} from './views/feed.js';
import {renderLibrary,bindLibrary} from './views/library.js';
import {renderCompete,bindCompete} from './views/compete.js';
import {renderRewards,bindRewards} from './views/rewards.js';
import {renderPremium,bindPremium} from './views/premium.js';
import {renderAccount,bindAccount} from './views/account.js';
import {renderSupport,bindSupport} from './views/support.js';
const routes={home:[renderHome,bindHome],feed:[renderFeed,bindFeed],library:[renderLibrary,bindLibrary],compete:[renderCompete,bindCompete],rewards:[renderRewards,bindRewards],premium:[renderPremium,bindPremium],account:[renderAccount,bindAccount],support:[renderSupport,bindSupport]};
const app=document.querySelector('#app');const balance=document.querySelector('#coin-balance');const network=document.querySelector('#network-status');let current='';
function route(){const name=location.hash.replace(/^#\//,'').split(/[/?]/)[0]||'home';return routes[name]?name:'home';}
function render(force=false){const name=route();if(force||name!==current){current=name;const [view,bind]=routes[name];app.innerHTML=view();bind?.();document.querySelectorAll('[data-route]').forEach(link=>link.classList.toggle('active',link.dataset.route===name));app.focus({preventScroll:true});track('route_view',{route:name});}const state=getState();balance.textContent=Number(state.coins||0).toLocaleString('en-PK');document.querySelector('#profile-button').textContent=state.user?(state.user.displayName||'P').slice(0,2).toUpperCase():'GA';document.querySelector('#premium-button').hidden=state.entitlement==='premium';document.documentElement.classList.toggle('reduce-motion',state.settings.reducedMotion);}
function setNetwork(){const online=navigator.onLine;network.textContent=online?'Online':'Offline';network.classList.toggle('offline',!online);}
async function hydrate(){try{const session=await getSession();if(session.authenticated)update({user:session.user,entitlement:session.entitlement?.tier||session.entitlement,coins:session.coins});}catch{}}
async function reconcilePayment(){const match=location.hash.match(/payment-return\?(.+)$/);const pending=JSON.parse(sessionStorage.getItem('game-arena:pending-payment')||'null');const query=match?new URLSearchParams(match[1]):null;const transactionId=query?.get('transactionId')||pending?.transactionId;if(!transactionId)return;const kind=query?.get('kind')||pending?.kind||'membership';try{if(kind==='topup'){for(let attempt=0;attempt<12;attempt++){const result=await paymentStatus(transactionId);if(result.status==='paid'){const wallet=await fetchWallet();update({coins:wallet.balance,walletEntries:wallet.entries||[],walletLoaded:true});sessionStorage.removeItem('game-arena:pending-payment');toast(`+${result.coins||pending?.coins||0} Arena Coins`);location.hash='#/rewards';return;}if(['failed','refunded','voided'].includes(result.status))throw new Error(`Payment ${result.status}.`);await new Promise(resolve=>setTimeout(resolve,2000));}toast('Top-up payment is pending confirmation.');location.hash='#/rewards';return;}const entitlement=await refreshEntitlement(transactionId,{attempts:15,intervalMs:2000});if(entitlement.status==='active'){update({entitlement:entitlement.entitlement,selectedPlan:pending?.planId||getState().selectedPlan});sessionStorage.removeItem('game-arena:pending-payment');track('checkout_complete',{planId:pending?.planId});toast('Game Arena+ is active');location.hash='#/account';}else{toast('Payment is pending confirmation.');location.hash='#/premium';}}catch(error){toast(error.message);location.hash=kind==='topup'?'#/rewards':'#/premium';}}
function registerServiceWorker(){navigator.serviceWorker.register(`/sw.js?release=${encodeURIComponent(releaseSha())}`,{updateViaCache:'none'}).catch(()=>{});}
addEventListener('hashchange',()=>{if(location.hash.startsWith('#/payment-return'))reconcilePayment();else render();});addEventListener('online',setNetwork);addEventListener('offline',setNetwork);addEventListener('beforeinstallprompt',event=>{event.preventDefault();window.__GAME_ARENA_INSTALL_PROMPT=event;update({installPromptAvailable:true});});document.querySelector('#profile-button').addEventListener('click',()=>location.hash='#/account');document.querySelector('#coins-button').addEventListener('click',()=>location.hash='#/rewards');document.querySelector('#premium-button').addEventListener('click',()=>location.hash='#/premium');subscribe(()=>render(true));observeVitals();observeErrors();setNetwork();await hydrate();if(!location.hash)location.replace('#/home');else if(location.hash.startsWith('#/payment-return'))reconcilePayment();else render();if('serviceWorker'in navigator){if(document.readyState==='complete')registerServiceWorker();else addEventListener('load',registerServiceWorker,{once:true});}
