import {getState,subscribe,update} from './state.js';
import {observeVitals,observeErrors,track} from './analytics.js';
import {getSession,refreshEntitlement} from './api.js';
import {toast} from './ui.js';
import {renderFeed,bindFeed} from './views/feed.js';
import {renderLibrary,bindLibrary} from './views/library.js';
import {renderPremium,bindPremium} from './views/premium.js';
import {renderRewards,bindRewards} from './views/rewards.js';
import {renderAccount,bindAccount} from './views/account.js';
const routes={feed:[renderFeed,bindFeed],library:[renderLibrary,bindLibrary],rewards:[renderRewards,bindRewards],premium:[renderPremium,bindPremium],account:[renderAccount,bindAccount]};const app=document.querySelector('#app');const balance=document.querySelector('#coin-balance');const network=document.querySelector('#network-status');let current='';
function route(){const name=location.hash.replace(/^#\//,'').split(/[/?]/)[0]||'feed';return routes[name]?name:'feed';}
function render(force=false){const name=route();if(force||name!==current){current=name;const [view,bind]=routes[name];app.innerHTML=view();bind?.();document.querySelectorAll('[data-route]').forEach(link=>link.classList.toggle('active',link.dataset.route===name));app.focus({preventScroll:true});track('route_view',{route:name});}const state=getState();balance.textContent=Number(state.coins||0).toLocaleString('en-PK');document.querySelector('#profile-button').textContent=state.user?'P1':'GA';}
function setNetwork(){const online=navigator.onLine;network.textContent=online?'Online':'Offline';network.classList.toggle('offline',!online);}
async function hydrate(){try{const session=await getSession();if(session.authenticated)update({user:session.user,entitlement:session.entitlement?.tier||session.entitlement,coins:session.coins});}catch{}}
async function reconcilePayment(){const match=location.hash.match(/payment-return\?(.+)$/);const pending=JSON.parse(sessionStorage.getItem('game-arena:pending-payment')||'null');const query=match?new URLSearchParams(match[1]):null;const transactionId=query?.get('transactionId')||pending?.transactionId;if(!transactionId)return;try{const entitlement=await refreshEntitlement(transactionId,{attempts:15,intervalMs:2000});if(entitlement.status==='active'){update({entitlement:entitlement.entitlement,selectedPlan:pending?.planId||getState().selectedPlan});sessionStorage.removeItem('game-arena:pending-payment');track('checkout_complete',{planId:pending?.planId});toast('Game Arena+ is active');location.hash='#/account';}else{toast('Payment is pending confirmation.');location.hash='#/premium';}}catch(error){toast(error.message);location.hash='#/premium';}}
addEventListener('hashchange',()=>{if(location.hash.startsWith('#/payment-return'))reconcilePayment();else render();});addEventListener('online',setNetwork);addEventListener('offline',setNetwork);document.querySelector('#profile-button').addEventListener('click',()=>location.hash='#/account');document.querySelector('#coins-button').addEventListener('click',()=>location.hash='#/rewards');subscribe(()=>render(true));observeVitals();observeErrors();setNetwork();await hydrate();if(!location.hash)location.replace('#/feed');else if(location.hash.startsWith('#/payment-return'))reconcilePayment();else render();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
