import {getState,update} from './state.js';
import {requestOtp,verifyOtp,createCheckout,refreshEntitlement,submitCheckout} from './api.js';
import {track} from './analytics.js';
const modalRoot=document.querySelector('#modal-root');const toastRoot=document.querySelector('#toast-root');
export function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}
export function money(value){return new Intl.NumberFormat('en-PK',{style:'currency',currency:'PKR',maximumFractionDigits:0}).format(value);}
export function toast(message){const node=document.createElement('div');node.className='toast';node.textContent=message;toastRoot.append(node);setTimeout(()=>node.remove(),3400);}
export function closeModal(){modalRoot.replaceChildren();}
export function modal(title,body,{wide=false}={}){modalRoot.innerHTML=`<div class="modal-backdrop" role="presentation"><section class="modal ${wide?'modal-wide':''}" role="dialog" aria-modal="true" aria-labelledby="modal-title"><header class="modal-head"><h2 id="modal-title">${escapeHtml(title)}</h2><button class="icon-button" data-close type="button" aria-label="Close">×</button></header>${body}</section></div>`;modalRoot.querySelector('[data-close]').addEventListener('click',closeModal);modalRoot.querySelector('.modal-backdrop').addEventListener('click',event=>{if(event.target===event.currentTarget)closeModal();});modalRoot.querySelector('input,button')?.focus();return modalRoot.querySelector('.modal');}
export function requireAuth(continuation){if(getState().user)return Promise.resolve(true);update({continuation});return new Promise(resolve=>{modal('Sign in to continue',`<form id="auth-form" class="stack"><p class="muted">Use a Pakistani mobile number or email. Demo OTP: <b>123456</b>.</p><div class="field"><label for="identifier">Mobile number or email</label><input id="identifier" name="identifier" autocomplete="username" required placeholder="03XX XXXXXXX"></div><button class="button primary" type="submit">Send OTP</button><p id="auth-status" role="status"></p></form>`);const form=document.querySelector('#auth-form');form.addEventListener('submit',async event=>{event.preventDefault();const status=form.querySelector('#auth-status');const identifier=new FormData(form).get('identifier');status.textContent='Sending code…';try{const challenge=await requestOtp(identifier);track('otp_request');form.innerHTML=`<p class="muted">Enter the six-digit verification code.</p><div class="field"><label for="otp">Verification code</label><input id="otp" name="otp" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" required></div><button class="button primary" type="submit">Verify</button><p id="auth-status" role="status"></p>`;form.onsubmit=async next=>{next.preventDefault();const output=form.querySelector('#auth-status');output.textContent='Verifying…';try{const result=await verifyOtp(challenge.challengeId,new FormData(form).get('otp'));update({user:result.user,entitlement:result.entitlement?.tier||result.entitlement||'free',coins:result.coins??getState().coins});track('otp_complete');closeModal();toast('Signed in successfully');resolve(true);}catch(error){output.textContent=error.message;}};form.querySelector('input').focus();}catch(error){status.textContent=error.message;}});});}
export async function membershipCheckout(plan){if(!await requireAuth({type:'checkout',planId:plan.id}))return;track('checkout_start',{planId:plan.id});modal('Activate Game Arena+',`<div class="stack"><div class="checkout-summary"><span><b>${escapeHtml(plan.name)}</b><small>${money(plan.price)} · fixed-duration ${escapeHtml(plan.period)}</small></span><span class="jazzcash-mark">JC</span></div><div class="notice">Game Arena never collects your JazzCash PIN or card details.</div><button class="button gold" id="start-payment" type="button">Continue to JazzCash</button><p id="payment-status" role="status"></p></div>`);document.querySelector('#start-payment').addEventListener('click',async()=>{const status=document.querySelector('#payment-status');status.textContent='Creating checkout…';try{const tx=await createCheckout(plan.id);sessionStorage.setItem('game-arena:pending-payment',JSON.stringify({transactionId:tx.transactionId,planId:plan.id,createdAt:Date.now()}));if(submitCheckout(tx.checkout)){status.textContent='Redirecting to JazzCash…';return;}status.textContent='Payment received. Confirming access…';const entitlement=await refreshEntitlement(tx.transactionId);if(entitlement.status!=='active'){status.textContent='Payment is still pending. You can safely return later.';return;}update({entitlement:entitlement.entitlement,selectedPlan:plan.id});sessionStorage.removeItem('game-arena:pending-payment');track('checkout_complete',{planId:plan.id});closeModal();toast('Game Arena+ is active');location.hash='#/account';}catch(error){status.textContent=error.message;}});}
