import {randomUUID} from 'node:crypto';
import {catalogue} from '../catalogue/index.mjs';
import {AuditLog,Metrics} from '../lib/observability.mjs';

export class MemoryStore{
  constructor({audit=new AuditLog(),metrics=new Metrics()}={}){
    this.audit=audit;this.metrics=metrics;this.users=new Map();this.usersByIdentity=new Map();this.identities=new Map();this.otp=new Map();this.sessions=new Map();this.devices=new Map();this.entitlements=new Map();this.entitlementHistory=[];this.transactions=new Map();this.paymentEvents=new Map();this.reconciliationCases=[];this.ledger=[];this.playSessions=new Map();this.rateLimits=new Map();this.games=catalogue.map(game=>({...game,version:game.version||'external'}));this.scoreEvents=[];this.adjustments=new Map();
    this.challenges=new Map([
      ['daily-play',{id:'daily-play',title:'Daily Play',gameIds:this.games.filter(item=>item.tier==='free').slice(0,10).map(item=>item.id),startsAt:0,endsAt:4102444800000,target:{type:'completions',value:3},reward:40,premium:false,status:'live'}],
      ['arena-plus-week',{id:'arena-plus-week',title:'Arena+ Week',gameIds:this.games.filter(item=>item.tier==='premium').slice(0,10).map(item=>item.id),startsAt:0,endsAt:4102444800000,target:{type:'score',value:1000},reward:250,premium:true,status:'live'}]
    ]);
    this.tournaments=new Map([['weekend-arena',{id:'weekend-arena',title:'Weekend Arena',gameId:this.games[0]?.id,startsAt:0,endsAt:4102444800000,premium:true,status:'open',maxEntries:10000,rewardPolicy:{type:'coins',top:[500,300,200]}}]]);this.tournamentEntries=[];
  }
  hitRateLimit(key,limit,windowMs,now=Date.now()){const recent=(this.rateLimits.get(key)??[]).filter(time=>time>now-windowMs);recent.push(now);this.rateLimits.set(key,recent);return recent.length>limit;}
  createOtp(challenge){this.otp.set(challenge.id,challenge);return challenge;} getOtp(id){return this.otp.get(id);} saveOtp(challenge){this.otp.set(challenge.id,challenge);}
  findOrCreateUser(identity){const identityKey=`${identity.type}:${identity.value}`;let id=this.usersByIdentity.get(identityKey);if(!id){id=randomUUID();const now=new Date().toISOString();const user={id,displayName:'Player',status:'active',createdAt:now,updatedAt:now,deletionRequestedAt:null};this.users.set(id,user);this.usersByIdentity.set(identityKey,id);this.identities.set(identityKey,{userId:id,...identity,verifiedAt:now,createdAt:now});this.setEntitlement(id,{tier:'free',status:'active',sourceType:'system',startsAt:Date.now()});this.audit.write({actor:id,action:'account.created',targetType:'user',targetId:id,metadata:{identityType:identity.type}});}return this.users.get(id);}
  linkIdentity(userId,identity){const key=`${identity.type}:${identity.value}`;const owner=this.usersByIdentity.get(key);if(owner&&owner!==userId)throw Object.assign(new Error('This identity belongs to another account.'),{status:409,code:'identity_conflict'});this.usersByIdentity.set(key,userId);this.identities.set(key,{userId,...identity,verifiedAt:new Date().toISOString(),createdAt:new Date().toISOString()});this.audit.write({actor:userId,action:'account.identity_linked',targetType:'user',targetId:userId,metadata:{identityType:identity.type}});}
  createSession(session){this.sessions.set(session.hash,session);this.devices.set(`${session.userId}:${session.deviceHash}`,{userId:session.userId,deviceHash:session.deviceHash,lastIpHash:session.ipHash,firstSeenAt:session.createdAt,lastSeenAt:session.createdAt,risk:session.risk||'normal'});return session;}
  getSession(hash){const session=this.sessions.get(hash);if(!session||session.revokedAt||session.expiresAt<Date.now())return null;session.lastSeenAt=Date.now();const device=this.devices.get(`${session.userId}:${session.deviceHash}`);if(device)device.lastSeenAt=Date.now();return session;}
  saveSession(oldHash,session){if(oldHash&&oldHash!==session.hash)this.sessions.delete(oldHash);this.sessions.set(session.hash,session);return session;}
  deleteSession(hash,reason='logout'){const session=this.sessions.get(hash);if(session){session.revokedAt=Date.now();session.revocationReason=reason;this.audit.write({actor:session.userId,action:'session.revoked',targetType:'session',targetId:session.id,metadata:{reason}});}this.sessions.delete(hash);}
  revokeUserSessions(userId,{exceptHash=null,reason='logout_all'}={}){let count=0;for(const [hash,session] of this.sessions)if(session.userId===userId&&hash!==exceptHash){this.deleteSession(hash,reason);count++;}return count;}
  listSessions(userId){return[...this.sessions.values()].filter(item=>item.userId===userId&&!item.revokedAt&&item.expiresAt>Date.now()).map(item=>({id:item.id,createdAt:item.createdAt,lastSeenAt:item.lastSeenAt,expiresAt:item.expiresAt,risk:item.risk,deviceHash:item.deviceHash.slice(0,12)}));}
  getUser(id){const user=this.users.get(id);return user?.status==='deleted'?null:user??null;}
  getEntitlement(userId,now=Date.now()){const current=this.entitlements.get(userId);if(current?.expiresAt&&current.expiresAt<=now&&current.status==='active'){const expired={...current,status:'expired',updatedAt:now};this.entitlements.set(userId,expired);this.entitlementHistory.push(expired);return expired;}return current??{tier:'free',status:'active'};}
  setEntitlement(userId,value){const item={id:value.id||randomUUID(),userId,...value,updatedAt:Date.now(),createdAt:value.createdAt||Date.now()};this.entitlements.set(userId,item);this.entitlementHistory.push(structuredClone(item));this.audit.write({actor:'system',action:'entitlement.changed',targetType:'user',targetId:userId,metadata:{tier:item.tier,status:item.status,sourceType:item.sourceType,sourceId:item.sourceId}});return item;}
  entitlementTimeline(userId){return this.entitlementHistory.filter(item=>item.userId===userId).map(item=>structuredClone(item));}
  listGames({includePaused=false}={}){return this.games.filter(game=>includePaused||game.status==='live');} getGame(id){return this.games.find(game=>game.id===id&&game.status==='live')??null;}
  saveGame(game){const index=this.games.findIndex(item=>item.id===game.id);if(index<0)this.games.push(game);else this.games[index]=game;return game;}
  createTransaction(tx){this.transactions.set(tx.id,tx);return tx;} getTransaction(id){return this.transactions.get(id)??null;} saveTransaction(tx){tx.updatedAt=new Date().toISOString();this.transactions.set(tx.id,tx);return tx;}
  findTransactionByIdempotency(key){return[...this.transactions.values()].find(item=>item.idempotencyKey===key)??null;}
  addPaymentEvent(event){if(event.providerEventId&&this.paymentEvents.has(event.providerEventId))return{duplicate:true,event:this.paymentEvents.get(event.providerEventId)};const id=event.providerEventId||randomUUID();this.paymentEvents.set(id,{id,...event,receivedAt:new Date().toISOString()});return{duplicate:false,event:this.paymentEvents.get(id)};}
  createReconciliationCase(item){const record={id:randomUUID(),status:'open',createdAt:new Date().toISOString(),...item};this.reconciliationCases.push(record);this.audit.write({actor:'system',action:'payment.reconciliation_case_created',targetType:'transaction',targetId:item.transactionId,metadata:{reason:item.reason}});return record;}
  wallet(userId){return this.ledger.filter(entry=>entry.userId===userId).reduce((sum,entry)=>sum+entry.amount,0);}
  walletEntries(userId,{limit=100}={}){return this.ledger.filter(entry=>entry.userId===userId).slice(-Math.min(limit,500)).reverse().map(item=>structuredClone(item));}
  appendLedger(entry){const duplicate=this.ledger.find(item=>item.idempotencyKey===entry.idempotencyKey);if(duplicate)return{...duplicate,duplicate:true};const record={id:entry.id||randomUUID(),createdAt:entry.createdAt||new Date().toISOString(),...entry};this.ledger.push(record);this.audit.write({actor:'system',action:'coins.ledger_appended',targetType:'user',targetId:entry.userId,metadata:{amount:entry.amount,reason:entry.reason,referenceType:entry.referenceType,referenceId:entry.referenceId}});return record;}
  dailyCredits(userId,since){return this.ledger.filter(item=>item.userId===userId&&item.amount>0&&new Date(item.createdAt).getTime()>=since).reduce((sum,item)=>sum+item.amount,0);}
  createPlaySession(session){this.playSessions.set(session.id,session);return session;} getPlaySession(id){return this.playSessions.get(id)??null;} savePlaySession(session){this.playSessions.set(session.id,session);return session;}
  addScore(event){if(this.scoreEvents.some(item=>item.playSessionId===event.playSessionId))return false;this.scoreEvents.push(event);return true;}
  leaderboard(gameId,{limit=100}={}){const best=new Map();for(const item of this.scoreEvents.filter(score=>score.gameId===gameId&&score.status==='verified')){const prior=best.get(item.userId);if(!prior||item.score>prior.score||(item.score===prior.score&&item.durationMs<prior.durationMs))best.set(item.userId,item);}return[...best.values()].sort((a,b)=>b.score-a.score||a.durationMs-b.durationMs||a.completedAt-b.completedAt).slice(0,limit).map((item,index)=>({rank:index+1,userId:item.userId,displayName:this.users.get(item.userId)?.displayName||'Player',score:item.score,durationMs:item.durationMs}));}
  challengeProgress(userId,challengeId){const challenge=this.challenges.get(challengeId);if(!challenge)return null;const sessions=[...this.playSessions.values()].filter(item=>item.userId===userId&&item.status==='completed'&&challenge.gameIds.includes(item.gameId)&&item.completedAt>=challenge.startsAt&&item.completedAt<=challenge.endsAt);const value=challenge.target.type==='completions'?sessions.length:sessions.reduce((sum,item)=>sum+(item.score||0),0);return{challengeId,value,target:challenge.target.value,complete:value>=challenge.target.value};}
  joinTournament(userId,tournamentId){const tournament=this.tournaments.get(tournamentId);if(!tournament)throw new Error('tournament not found');const existing=this.tournamentEntries.find(item=>item.userId===userId&&item.tournamentId===tournamentId);if(existing)return existing;if(this.tournamentEntries.filter(item=>item.tournamentId===tournamentId).length>=tournament.maxEntries)throw new Error('tournament full');const entry={id:randomUUID(),userId,tournamentId,joinedAt:Date.now(),status:'eligible'};this.tournamentEntries.push(entry);return entry;}
  exportAccount(userId){const user=this.users.get(userId);return{exportedAt:new Date().toISOString(),user,identities:[...this.identities.values()].filter(item=>item.userId===userId).map(item=>({type:item.type,masked:item.type==='phone'?`${item.value.slice(0,4)}******${item.value.slice(-2)}`:item.value.replace(/^(.).+(@.+)$/,'$1***$2'),verifiedAt:item.verifiedAt})),sessions:this.listSessions(userId),entitlements:this.entitlementTimeline(userId),wallet:{balance:this.wallet(userId),entries:this.walletEntries(userId,{limit:500})},plays:[...this.playSessions.values()].filter(item=>item.userId===userId)};}
  requestDeletion(userId,now=Date.now()){const user=this.users.get(userId);if(!user)return false;user.status='deletion_pending';user.deletionRequestedAt=now;this.revokeUserSessions(userId,{reason:'account_deletion'});this.audit.write({actor:userId,action:'account.deletion_requested',targetType:'user',targetId:userId});return true;}
}
