import {Pool} from 'pg';
import {MemoryStore} from './memory-store.mjs';
import {AuditLog,Metrics} from '../lib/observability.mjs';
const MAP_FIELDS=['users','usersByIdentity','identities','otp','sessions','devices','entitlements','transactions','paymentEvents','playSessions','rateLimits','challenges','tournaments','adjustments'];
const ARRAY_FIELDS=['entitlementHistory','reconciliationCases','ledger','games','scoreEvents','tournamentEntries'];
const MUTATIONS=['createOtp','saveOtp','findOrCreateUser','linkIdentity','createSession','saveSession','deleteSession','revokeUserSessions','setEntitlement','saveGame','createTransaction','saveTransaction','addPaymentEvent','createReconciliationCase','appendLedger','createPlaySession','savePlaySession','addScore','joinTournament','requestDeletion'];
function encode(store){const state={schemaVersion:1};for(const field of MAP_FIELDS)state[field]=[...store[field].entries()];for(const field of ARRAY_FIELDS)state[field]=store[field];state.audit=store.audit.events;state.metrics={counters:[...store.metrics.counters.entries()],timings:[...store.metrics.timings.entries()]};return state;}
function restore(store,state){if(!state||state.schemaVersion!==1)return;for(const field of MAP_FIELDS)if(Array.isArray(state[field]))store[field]=new Map(state[field]);for(const field of ARRAY_FIELDS)if(Array.isArray(state[field]))store[field]=state[field];store.audit.events=Array.isArray(state.audit)?state.audit:[];store.metrics.counters=new Map(state.metrics?.counters||[]);store.metrics.timings=new Map(state.metrics?.timings||[]);}
export class PostgresStore extends MemoryStore{
  static async connect({connectionString,ssl=false}){const pool=new Pool({connectionString,max:10,idleTimeoutMillis:30000,connectionTimeoutMillis:10000,ssl:ssl?{rejectUnauthorized:false}:undefined});await pool.query('SELECT 1');await pool.query(`CREATE TABLE IF NOT EXISTS platform_state (id text PRIMARY KEY, revision bigint NOT NULL DEFAULT 0, state jsonb NOT NULL, updated_at timestamptz NOT NULL DEFAULT now())`);const result=await pool.query('SELECT revision,state FROM platform_state WHERE id=$1',['primary']);const store=new PostgresStore({pool});if(result.rows[0]){restore(store,result.rows[0].state);store.revision=Number(result.rows[0].revision);}store.dirty=false;return store;}
  constructor({pool}){super({audit:new AuditLog(),metrics:new Metrics()});this.pool=pool;this.revision=0;this.dirty=false;this.flushing=null;for(const name of MUTATIONS){const original=this[name].bind(this);this[name]=(...args)=>{const result=original(...args);this.markDirty();return result;};}}
  markDirty(){this.dirty=true;if(!this.flushing)this.flushing=Promise.resolve().then(()=>this.flush()).catch(error=>{this.dirty=true;console.error(JSON.stringify({level:'error',message:'PostgreSQL state flush failed',error:error.message}));}).finally(()=>{this.flushing=null;});}
  async flush(){if(!this.dirty)return;const state=encode(this);const client=await this.pool.connect();try{await client.query('BEGIN');await client.query('SELECT pg_advisory_xact_lock($1)',[194260730]);const current=await client.query('SELECT revision FROM platform_state WHERE id=$1 FOR UPDATE',['primary']);const revision=current.rows[0]?Number(current.rows[0].revision):0;if(revision!==this.revision)throw new Error('Concurrent platform state writer detected; production API must run a single writer replica.');const next=revision+1;await client.query(`INSERT INTO platform_state(id,revision,state,updated_at) VALUES($1,$2,$3,now()) ON CONFLICT(id) DO UPDATE SET revision=EXCLUDED.revision,state=EXCLUDED.state,updated_at=now()`,['primary',next,state]);await client.query('COMMIT');this.revision=next;this.dirty=false;}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}
  async close(){if(this.flushing)await this.flushing;await this.flush();await this.pool.end();}
}
