import {readFile} from 'node:fs/promises';
import {Pool} from 'pg';
import {MemoryStore} from './memory-store.mjs';
import {AuditLog,Metrics} from '../lib/observability.mjs';
const MAP_FIELDS=['users','usersByIdentity','identities','otp','sessions','devices','entitlements','transactions','paymentEvents','playSessions','rateLimits','challenges','tournaments','adjustments','multiplayerRooms'];
const ARRAY_FIELDS=['entitlementHistory','reconciliationCases','ledger','games','scoreEvents','tournamentEntries','supportTickets','voucherRedemptions'];
const MUTATIONS=['hitRateLimit','createOtp','saveOtp','findOrCreateUser','linkIdentity','createSession','getSession','saveSession','deleteSession','revokeUserSessions','getEntitlement','setEntitlement','saveGame','createTransaction','saveTransaction','addPaymentEvent','createReconciliationCase','appendLedger','createPlaySession','savePlaySession','addScore','joinTournament','createMultiplayerRoom','joinMultiplayerRoom','redeemVoucher','createSupportTicket','requestDeletion'];
async function certificate(input){if(input)return input;try{return await readFile('/app/certs/rds-global-bundle.pem','utf8');}catch{throw new Error('A trusted RDS CA bundle is required when PostgreSQL TLS is enabled.');}}
function encode(store){const state={schemaVersion:2};for(const field of MAP_FIELDS)state[field]=[...store[field].entries()];for(const field of ARRAY_FIELDS)state[field]=store[field];state.audit=store.audit.events;state.metrics={counters:[...store.metrics.counters.entries()],timings:[...store.metrics.timings.entries()]};return structuredClone(state);}
function restore(store,state){if(!state||![1,2].includes(state.schemaVersion))return;for(const field of MAP_FIELDS)if(Array.isArray(state[field]))store[field]=new Map(state[field]);for(const field of ARRAY_FIELDS)if(Array.isArray(state[field]))store[field]=state[field];store.audit.events=Array.isArray(state.audit)?state.audit:[];store.metrics.counters=new Map(state.metrics?.counters||[]);store.metrics.timings=new Map(state.metrics?.timings||[]);}
export class PostgresStore extends MemoryStore{
  static async connect({connectionString,ssl=false,ca=''}){const trustedCa=ssl?await certificate(ca):'';const pool=new Pool({connectionString,max:10,idleTimeoutMillis:30000,connectionTimeoutMillis:10000,ssl:ssl?{ca:trustedCa,rejectUnauthorized:true}:undefined});await pool.query('SELECT 1');await pool.query(`CREATE TABLE IF NOT EXISTS platform_state (id text PRIMARY KEY, revision bigint NOT NULL DEFAULT 0, state jsonb NOT NULL, updated_at timestamptz NOT NULL DEFAULT now())`);const result=await pool.query('SELECT revision,state FROM platform_state WHERE id=$1',['primary']);const store=new PostgresStore({pool});if(result.rows[0]){restore(store,result.rows[0].state);store.revision=Number(result.rows[0].revision);}store.persistedVersion=store.mutationVersion;return store;}
  constructor({pool}){super({audit:new AuditLog(),metrics:new Metrics()});this.pool=pool;this.revision=0;this.mutationVersion=0;this.persistedVersion=0;this.commitPromise=null;for(const name of MUTATIONS){const original=this[name].bind(this);this[name]=(...args)=>{const result=original(...args);this.markDirty();return result;};}}
  markDirty(){this.mutationVersion+=1;}
  async commit(){if(this.persistedVersion===this.mutationVersion)return;if(!this.commitPromise)this.commitPromise=this.flushLoop().finally(()=>{this.commitPromise=null;});await this.commitPromise;if(this.persistedVersion!==this.mutationVersion)return this.commit();}
  async flushLoop(){while(this.persistedVersion!==this.mutationVersion){const targetVersion=this.mutationVersion;const state=encode(this);const client=await this.pool.connect();try{await client.query('BEGIN');await client.query('SELECT pg_advisory_xact_lock($1)',[194260730]);const current=await client.query('SELECT revision FROM platform_state WHERE id=$1 FOR UPDATE',['primary']);const revision=current.rows[0]?Number(current.rows[0].revision):0;if(revision!==this.revision)throw new Error('Concurrent platform state writer detected; production API must run a single writer replica.');const next=revision+1;await client.query(`INSERT INTO platform_state(id,revision,state,updated_at) VALUES($1,$2,$3,now()) ON CONFLICT(id) DO UPDATE SET revision=EXCLUDED.revision,state=EXCLUDED.state,updated_at=now()`,['primary',next,state]);await client.query('COMMIT');this.revision=next;this.persistedVersion=targetVersion;}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}}
  async close(){await this.commit();await this.pool.end();}
}
