export default [
  {
    id:'duck-hunter',
    title:'Duck Hunter',
    genre:'Arcade',
    tier:'free',
    orientation:'landscape',
    description:'Controlled-origin pilot pending staging certification.',
    reward:0,
    version:'1.0.0-pilot.1',
    status:'paused',
    rolloutPercentage:0,
    multiplayer:false,
    sourceType:'controlled-pilot',
    rewardsEnabled:false,
    competitionsEnabled:false
  },
  {
    id:'ranger-vs-zombies',
    title:'Ranger vs Zombies',
    genre:'Action',
    tier:'premium',
    orientation:'landscape',
    description:'Controlled-origin pilot pending staging certification.',
    reward:0,
    version:'1.0.0-pilot.1',
    status:'paused',
    rolloutPercentage:0,
    multiplayer:false,
    sourceType:'controlled-pilot',
    rewardsEnabled:false,
    competitionsEnabled:false
  },
  {
    id:'robotex',
    title:'Robotex',
    genre:'Action',
    tier:'premium',
    orientation:'landscape',
    description:'Controlled-origin pilot pending staging certification.',
    reward:0,
    version:'1.0.0-pilot.1',
    status:'paused',
    rolloutPercentage:0,
    multiplayer:false,
    sourceType:'controlled-pilot',
    rewardsEnabled:false,
    competitionsEnabled:false
  },
  {
    id:'swat-vs-zombies',
    title:'Swat vs Zombies',
    genre:'Action',
    tier:'premium',
    orientation:'landscape',
    description:'Controlled-origin pilot pending staging certification.',
    reward:0,
    version:'1.0.0-pilot.1',
    status:'paused',
    rolloutPercentage:0,
    multiplayer:false,
    sourceType:'controlled-pilot',
    rewardsEnabled:false,
    competitionsEnabled:false
  }
];
