const config={apiBaseUrl:'/api',authMode:'gateway',...(window.GAME_ARENA_ADMIN_CONFIG||{})};let localKey='';let role='admin';let current='overview';const view=document.querySelector('#view');const consoleRoot=document.querySelector('#console');const authRoot=document.querySelector('#auth');const escape=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
function toast(message){const node=document.querySelector('#toast');node.textContent=message;node.classList.add('show');setTimeout(()=>node.classList.remove('show'),2500);}
async function request(path,options={}){const headers={'content-type':'application/json','x-admin-request':'1','x-admin-role':role,...(localKey?{'x-admin-key':localKey}:{}),...(options.headers||{})};const response=await fetch(`${config.apiBaseUrl}${path}`,{credentials:'include',...options,headers});const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.error?.message||`Request failed: ${response.status}`);return data;}
const metric=(label,value)=>`<div class="metric"><b>${escape(value)}</b><span>${escape(label)}</span></div>`;
async function overview(){const [metrics,payments,games,reviews]=await Promise.all([request('/v1/admin/metrics'),request('/v1/admin/payments'),request('/v1/admin/games'),request('/v1/admin/reviews')]);const counters=Object.values(metrics.counters||{}).reduce((sum,value)=>sum+Number(value||0),0);view.innerHTML=`<h1>Overview</h1><div class="grid">${metric('Recorded metrics',counters)}${metric('Transactions',payments.transactions.length)}${metric('Open reconciliation',payments.reconciliationCases.filter(item=>item.status==='open').length)}${metric('Live games',games.games.filter(item=>item.state==='live'||item.status==='live').length)}${metric('Results in review',reviews.results.length)}</div><h2>Provider health</h2><pre>${escape(JSON.stringify(metrics,null,2))}</pre>`;}
async function users(){view.innerHTML=`<h1>Users</h1><form id="user-search"><label>Search account ID or display name<input name="q"></label><button>Search</button></form><div id="user-results"></div>`;const run=async()=>{const q=new FormData(document.querySelector('#user-search')).get('q');const data=await request(`/v1/admin/users?q=${encodeURIComponent(q)}`);document.querySelector('#user-results').innerHTML=`<div class="scroll"><table><thead><tr><th>User</th><th>Identity</th><th>Entitlement</th><th>Coins</th><th>Status</th><th>Actions</th></tr></thead><tbody>${data.users.map(user=>`<tr><td>${escape(user.displayName)}<br><small>${escape(user.id)}</small></td><td>${user.identities.map(item=>`${escape(item.type)}: ${escape(item.value)}`).join('<br>')}</td><td>${escape(user.entitlement.tier)} / ${escape(user.entitlement.status)}</td><td>${escape(user.coins)}</td><td>${escape(user.status)}</td><td><button data-adjust="${user.id}">Adjust coins</button></td></tr>`).join('')}</tbody></table></div>`;document.querySelectorAll('[data-adjust]').forEach(button=>button.onclick=()=>adjustCoins(button.dataset.adjust));};document.querySelector('#user-search').onsubmit=event=>{event.preventDefault();run().catch(error=>toast(error.message));};await run();}
async function adjustCoins(userId){const amount=Number(prompt('Coin adjustment amount (negative removes coins):'));if(!Number.isInteger(amount)||amount===0)return;const reason=prompt('Required reason:');if(!reason)return;const result=await request('/v1/admin/coins/adjustments',{method:'POST',body:JSON.stringify({userId,amount,reason})});toast(result.adjustment?'Adjustment needs second approval.':'Adjustment applied.');await users();}
async function payments(){const data=await request('/v1/admin/payments');view.innerHTML=`<h1>Payments</h1><h2>Transactions</h2><div class="scroll"><table><thead><tr><th>ID</th><th>User</th><th>Plan</th><th>Amount</th><th>Status</th><th>Reference</th></tr></thead><tbody>${data.transactions.map(item=>`<tr><td>${escape(item.id)}</td><td>${escape(item.userId)}</td><td>${escape(item.planId)}</td><td>PKR ${escape(item.amountPkr)}</td><td>${escape(item.status)}</td><td>${escape(item.providerReference||'')}</td></tr>`).join('')}</tbody></table></div><h2>Reconciliation cases</h2><pre>${escape(JSON.stringify(data.reconciliationCases,null,2))}</pre>`;}
async function games(){const data=await request('/v1/admin/games');view.innerHTML=`<h1>Games</h1><div class="scroll"><table><thead><tr><th>Game</th><th>State</th><th>Active version</th><th>Rollout</th><th>Actions</th></tr></thead><tbody>${data.games.map(game=>`<tr><td>${escape(game.title)}<br><small>${escape(game.id)}</small></td><td>${escape(game.state||game.status)}</td><td>${escape(game.activeVersion||game.version)}</td><td>${escape(game.rolloutPercentage??100)}%</td><td class="actions"><button data-state="live" data-id="${game.id}">Live</button><button data-state="paused" data-id="${game.id}">Pause</button><button data-state="retired" data-id="${game.id}" class="danger">Retire</button></td></tr>`).join('')}</tbody></table></div>`;document.querySelectorAll('[data-state]').forEach(button=>button.onclick=async()=>{const reason=prompt(`Reason to set ${button.dataset.id} to ${button.dataset.state}:`);if(!reason)return;try{await request(`/v1/admin/games/${button.dataset.id}/state`,{method:'POST',body:JSON.stringify({state:button.dataset.state,reason})});toast('Game state updated.');await games();}catch(error){toast(error.message);}});}
async function reviews(){const data=await request('/v1/admin/reviews');view.innerHTML=`<h1>Integrity reviews</h1><div class="scroll"><table><thead><tr><th>Session</th><th>User</th><th>Game</th><th>Score</th><th>Duration</th><th>Reasons</th></tr></thead><tbody>${data.results.map(item=>`<tr><td>${escape(item.playSessionId)}</td><td>${escape(item.userId)}</td><td>${escape(item.gameId)}</td><td>${escape(item.score)}</td><td>${escape(item.durationMs)} ms</td><td>${escape((item.reasons||[]).join(', '))}</td></tr>`).join('')}</tbody></table></div>`;}
async function audit(){const data=await request('/v1/admin/audit?limit=200');view.innerHTML=`<h1>Audit log</h1><div class="scroll"><table><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Target</th><th>Metadata</th></tr></thead><tbody>${data.events.slice().reverse().map(item=>`<tr><td>${escape(item.at)}</td><td>${escape(item.actor)}</td><td>${escape(item.action)}</td><td>${escape(item.targetType)} ${escape(item.targetId||'')}</td><td><pre>${escape(JSON.stringify(item.metadata))}</pre></td></tr>`).join('')}</tbody></table></div>`;}
const views={overview,users,payments,games,reviews,audit};async function load(name=current){current=name;view.innerHTML='<p>Loading…</p>';try{await views[name]();}catch(error){view.innerHTML=`<p class="error">${escape(error.message)}</p>`;}}
function enter(){authRoot.hidden=true;consoleRoot.hidden=false;load();}
document.querySelector('#local-auth').onsubmit=event=>{event.preventDefault();const data=new FormData(event.currentTarget);localKey=String(data.get('key')||'');role=String(data.get('role')||'admin');enter();};document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>load(button.dataset.view));document.querySelector('#refresh').onclick=()=>load();if(config.authMode==='gateway')enter();
