import {randomUUID} from 'node:crypto';
const PLANS={monthly:{price:299,durationMs:31*86400000},yearly:{price:4999,durationMs:366*86400000}};
const FINAL=new Set(['paid','failed','refunded','voided']);
const ALLOWED={pending:new Set(['pending','paid','failed','voided']),paid:new Set(['paid','refunded']),failed:new Set(['failed']),voided:new Set(['voided']),refunded:new Set(['refunded'])};
const fail=(message,status=409,code='payment_conflict')=>Object.assign(new Error(message),{status,code});
const fingerprint=value=>JSON.stringify(value,Object.keys(value).sort());
export class PaymentService{
  constructor({store,provider,clock=()=>Date.now()}){this.store=store;this.provider=provider;this.clock=clock;}
  plan(id){const plan=PLANS[id];if(!plan)throw Object.assign(new Error('Unknown premium plan.'),{status:400,code:'invalid_plan'});return plan;}
  scopedKey({userId,kind,productId,key}){const raw=String(key||'').trim();if(raw.length>200)throw Object.assign(new Error('Idempotency key is too long.'),{status:400,code:'invalid_idempotency_key'});return`${userId}:${kind}:${productId}:${raw||Math.floor(this.clock()/300000)}`;}
  existing(key,expected){const transaction=this.store.findTransactionByIdempotency(key);if(!transaction)return null;if(transaction.userId!==expected.userId||transaction.kind!==expected.kind||transaction.purchaseFingerprint!==expected.purchaseFingerprint)throw fail('Idempotency key was already used for another purchase.',409,'idempotency_conflict');return transaction;}
  async checkout({userId,planId,idempotencyKey}){const plan=this.plan(planId);const purchaseFingerprint=fingerprint({kind:'membership',planId,amountPkr:plan.price});const key=this.scopedKey({userId,kind:'membership',productId:planId,key:idempotencyKey});const prior=this.existing(key,{userId,kind:'membership',purchaseFingerprint});if(prior)return prior;const transaction={id:randomUUID(),kind:'membership',userId,provider:'JazzCash',planId,amountPkr:plan.price,currency:'PKR',status:'pending',idempotencyKey:key,purchaseFingerprint,createdAt:new Date(this.clock()).toISOString(),updatedAt:new Date(this.clock()).toISOString(),attempts:0};const provider=await this.provider.createCheckout({transactionId:transaction.id,referenceType:'membership',referenceId:planId,amountPkr:plan.price,description:`Game Arena+ ${planId}`});Object.assign(transaction,provider);this.store.createTransaction(transaction);this.store.audit.write({actor:userId,action:'payment.checkout_created',targetType:'transaction',targetId:transaction.id,metadata:{kind:'membership',planId,amountPkr:plan.price}});return transaction;}
  async checkoutTopup({userId,offer,idempotencyKey,isPremium=false}){const amountPkr=isPremium?Math.max(1,Math.round(offer.amountPkr*.9)):offer.amountPkr;const purchaseFingerprint=fingerprint({kind:'topup',offerId:offer.id,coins:offer.coins,amountPkr});const key=this.scopedKey({userId,kind:'topup',productId:offer.id,key:idempotencyKey});const prior=this.existing(key,{userId,kind:'topup',purchaseFingerprint});if(prior)return prior;const transaction={id:randomUUID(),kind:'topup',userId,provider:'JazzCash',offerId:offer.id,coins:offer.coins,amountPkr,currency:'PKR',status:'pending',idempotencyKey:key,purchaseFingerprint,createdAt:new Date(this.clock()).toISOString(),updatedAt:new Date(this.clock()).toISOString(),attempts:0};const provider=await this.provider.createCheckout({transactionId:transaction.id,referenceType:'topup',referenceId:offer.id,amountPkr,description:`Game Arena ${offer.label}`});Object.assign(transaction,provider);this.store.createTransaction(transaction);this.store.audit.write({actor:userId,action:'payment.checkout_created',targetType:'transaction',targetId:transaction.id,metadata:{kind:'topup',offerId:offer.id,coins:offer.coins,amountPkr,memberDiscount:isPremium}});return transaction;}
  assertExpected(transaction,event){const expected=transaction.expected||{};const mismatch=[];if(event.billReference!==transaction.id||expected.billReference&&event.billReference!==expected.billReference)mismatch.push('bill_reference');if(!Number.isFinite(event.amountMinor)||event.amountMinor!==Math.round(transaction.amountPkr*100)||expected.amountMinor!==undefined&&event.amountMinor!==expected.amountMinor)mismatch.push('amount');if(event.currency!==(transaction.currency||'PKR')||expected.currency&&event.currency!==expected.currency)mismatch.push('currency');if(expected.merchantId&&event.merchantId!==expected.merchantId)mismatch.push('merchant');if(mismatch.length)throw Object.assign(new Error('Payment notification does not match the stored transaction.'),{status:422,code:'payment_value_mismatch',details:{fields:mismatch}});}
  applyEvent({transactionId,status,providerReference,providerEventId,payload={},signatureValid,event={}}){const transaction=this.store.getTransaction(transactionId);if(!transaction)throw Object.assign(new Error('Unknown transaction.'),{status:404,code:'transaction_not_found'});const recorded=this.store.addPaymentEvent({transactionId,providerEventId,signatureValid,kind:status,payload});if(recorded.duplicate)return{transaction,duplicate:true};if(!signatureValid)throw Object.assign(new Error('Invalid payment signature.'),{status:401,code:'invalid_signature'});if(!ALLOWED[transaction.status]?.has(status)){this.store.createReconciliationCase({transactionId,reason:'invalid_transition',expected:transaction.status,received:status});return{transaction,duplicate:false,reconciled:true};}if(transaction.status===status)return{transaction,duplicate:false};if(status==='paid'){this.assertExpected(transaction,event);this.activate(transaction,providerReference);}else if(status==='failed'||status==='voided'){transaction.status=status;this.store.saveTransaction(transaction);}else if(status==='refunded')this.refund(transaction.id,{providerReference,reason:'provider_event'});return{transaction:this.store.getTransaction(transaction.id),duplicate:false};}
  activate(transaction,providerReference){transaction.status='paid';transaction.providerReference=providerReference||transaction.providerReference;transaction.paidAt=new Date(this.clock()).toISOString();if(transaction.kind==='topup'){this.store.saveTransaction(transaction);this.store.appendLedger({userId:transaction.userId,amount:transaction.coins,reason:'coin_topup',idempotencyKey:`topup:${transaction.id}`,referenceType:'transaction',referenceId:transaction.id});this.store.audit.write({actor:'system',action:'topup.paid',targetType:'transaction',targetId:transaction.id,metadata:{coins:transaction.coins,providerReference:transaction.providerReference}});return;}const plan=this.plan(transaction.planId);const current=this.store.getEntitlement(transaction.userId,this.clock());const base=current.tier==='premium'&&current.status==='active'&&current.expiresAt>this.clock()?current.expiresAt:this.clock();transaction.entitlementStartsAt=base;transaction.entitlementExpiresAt=base+plan.durationMs;this.store.saveTransaction(transaction);this.store.setEntitlement(transaction.userId,{tier:'premium',status:'active',sourceType:'payment',sourceId:transaction.id,startsAt:base,expiresAt:transaction.entitlementExpiresAt});this.store.audit.write({actor:'system',action:'payment.paid',targetType:'transaction',targetId:transaction.id,metadata:{providerReference:transaction.providerReference}});}
  recomputeMembership(userId){const valid=[...this.store.transactions.values()].filter(item=>item.userId===userId&&item.kind==='membership'&&item.status==='paid'&&item.entitlementExpiresAt>this.clock()).sort((a,b)=>b.entitlementExpiresAt-a.entitlementExpiresAt);if(valid.length){const source=valid[0];return this.store.setEntitlement(userId,{tier:'premium',status:'active',sourceType:'payment-recompute',sourceId:source.id,startsAt:this.clock(),expiresAt:source.entitlementExpiresAt});}return this.store.setEntitlement(userId,{tier:'free',status:'active',sourceType:'refund-recompute',startsAt:this.clock(),expiresAt:null});}
  refund(transactionId,{providerReference,reason='refund'}={}){const transaction=this.store.getTransaction(transactionId);if(!transaction||transaction.status!=='paid')throw Object.assign(new Error('Paid transaction not found.'),{status:409,code:'refund_not_allowed'});transaction.status='refunded';transaction.refundedAt=new Date(this.clock()).toISOString();transaction.refundReference=providerReference;this.store.saveTransaction(transaction);if(transaction.kind==='topup')this.store.appendLedger({userId:transaction.userId,amount:-transaction.coins,reason:'topup_refund',idempotencyKey:`topup-refund:${transaction.id}`,referenceType:'transaction',referenceId:transaction.id});else this.recomputeMembership(transaction.userId);this.store.audit.write({actor:'system',action:'payment.refunded',targetType:'transaction',targetId:transaction.id,metadata:{reason,kind:transaction.kind||'membership'}});return transaction;}
  reconcile(providerRecords=[]){const seen=new Set();const cases=[];for(const record of providerRecords){seen.add(record.transactionId);const internal=this.store.getTransaction(record.transactionId);if(!internal){cases.push(this.store.createReconciliationCase({transactionId:record.transactionId,reason:'provider_only',providerStatus:record.status}));continue;}if(internal.status!==record.status)cases.push(this.store.createReconciliationCase({transactionId:internal.id,reason:'status_mismatch',internalStatus:internal.status,providerStatus:record.status}));if(record.amountPkr!==undefined&&Number(record.amountPkr)!==internal.amountPkr)cases.push(this.store.createReconciliationCase({transactionId:internal.id,reason:'amount_mismatch',internalAmount:internal.amountPkr,providerAmount:record.amountPkr}));}for(const transaction of this.store.transactions.values())if(transaction.status==='pending'&&this.clock()-new Date(transaction.createdAt).getTime()>24*3600000&&!seen.has(transaction.id))cases.push(this.store.createReconciliationCase({transactionId:transaction.id,reason:'stale_pending'}));return cases;}
}
export {PLANS};
