import {randomUUID} from 'node:crypto';

const DAY_MS=86400000;
const PLAN_DEFINITIONS={
  monthly:{id:'monthly',name:'Game Arena+ Monthly',pricePkr:299,currency:'PKR',durationDays:31,durationMs:31*DAY_MS,billingMode:'single',benefitsVersion:'launch-v1'},
  yearly:{id:'yearly',name:'Game Arena+ Yearly',pricePkr:4999,currency:'PKR',durationDays:366,durationMs:366*DAY_MS,billingMode:'single',benefitsVersion:'launch-v1'}
};
const PLANS=Object.fromEntries(Object.entries(PLAN_DEFINITIONS).map(([id,plan])=>[id,{price:plan.pricePkr,durationMs:plan.durationMs}]));
const ALLOWED={pending:new Set(['pending','paid','failed','voided']),paid:new Set(['paid','refunded']),failed:new Set(['failed']),voided:new Set(['voided']),refunded:new Set(['refunded'])};
const fail=(message,status=409,code='payment_conflict')=>Object.assign(new Error(message),{status,code});
const fingerprint=value=>JSON.stringify(value,Object.keys(value).sort());
const iso=millis=>new Date(millis).toISOString();

function ensureReportingState(store){
  store.planVersions??=Object.values(PLAN_DEFINITIONS).map(plan=>({...plan,version:`${plan.id}-launch-v1`,status:'active',effectiveAt:'2026-07-30T00:00:00.000Z',retiredAt:null,scheduledAt:null}));
  store.benefitLedger??=[];
  store.reportExports??=[];
}

export class PaymentService{
  constructor({store,provider,clock=()=>Date.now()}){this.store=store;this.provider=provider;this.clock=clock;ensureReportingState(store);}
  plan(id){const plan=this.store.planVersions.find(item=>item.id===id&&item.status==='active')??PLAN_DEFINITIONS[id];if(!plan)throw Object.assign(new Error('Unknown premium plan.'),{status:400,code:'invalid_plan'});return{...plan,pricePkr:Number(plan.pricePkr??plan.price),durationMs:Number(plan.durationMs??Number(plan.durationDays)*DAY_MS),currency:plan.currency||'PKR'};}
  scopedKey({userId,kind,productId,key}){const raw=String(key||'').trim();if(raw.length>200)throw Object.assign(new Error('Idempotency key is too long.'),{status:400,code:'invalid_idempotency_key'});return`${userId}:${kind}:${productId}:${raw||Math.floor(this.clock()/300000)}`;}
  existing(key,expected){const transaction=this.store.findTransactionByIdempotency(key);if(!transaction)return null;if(transaction.userId!==expected.userId||transaction.kind!==expected.kind||transaction.purchaseFingerprint!==expected.purchaseFingerprint)throw fail('Idempotency key was already used for another purchase.',409,'idempotency_conflict');return transaction;}
  membershipPurpose(userId){const prior=[...this.store.transactions.values()].some(item=>item.userId===userId&&item.kind==='membership'&&item.status==='paid');return prior?'extension':'activation';}
  planSnapshot(plan){return{id:plan.id,name:plan.name,version:plan.version||`${plan.id}-launch-v1`,pricePkr:plan.pricePkr,currency:plan.currency,durationDays:plan.durationDays??Math.round(plan.durationMs/DAY_MS),durationMs:plan.durationMs,billingMode:plan.billingMode||'single',benefitsVersion:plan.benefitsVersion||'launch-v1'};}
  safeStoredProvider(provider={}){return{providerReference:provider.providerReference,expected:provider.expected?{merchantId:provider.expected.merchantId,billReference:provider.expected.billReference,amountMinor:provider.expected.amountMinor,currency:provider.expected.currency}:undefined};}
  async checkout({userId,planId,idempotencyKey}){
    const plan=this.plan(planId);const purpose=this.membershipPurpose(userId);const purchaseFingerprint=fingerprint({kind:'membership',planId,amountPkr:plan.pricePkr,purpose});const key=this.scopedKey({userId,kind:'membership',productId:planId,key:idempotencyKey});const prior=this.existing(key,{userId,kind:'membership',purchaseFingerprint});if(prior)return prior;
    const now=this.clock();const transaction={id:randomUUID(),kind:'membership',purpose,userId,provider:'JazzCash',planId,planSnapshot:this.planSnapshot(plan),listAmountPkr:plan.pricePkr,amountPkr:plan.pricePkr,discountPkr:0,currency:plan.currency,status:'pending',providerStatus:'pending',idempotencyKey:key,purchaseFingerprint,createdAt:iso(now),initiatedAt:iso(now),updatedAt:iso(now),attempts:1};
    const provider=await this.provider.createCheckout({transactionId:transaction.id,referenceType:'membership',referenceId:planId,amountPkr:plan.pricePkr,description:`Game Arena+ ${planId}`});Object.assign(transaction,this.safeStoredProvider(provider));this.store.createTransaction(transaction);this.store.audit.write({actor:userId,action:'payment.checkout_created',targetType:'transaction',targetId:transaction.id,metadata:{kind:'membership',purpose,planId,amountPkr:plan.pricePkr,currency:plan.currency}});return{...transaction,checkout:provider.checkout};
  }
  async checkoutTopup({userId,offer,idempotencyKey,isPremium=false}){
    const listAmountPkr=Number(offer.amountPkr);const amountPkr=isPremium?Math.max(1,Math.round(listAmountPkr*.9)):listAmountPkr;const discountPkr=Math.max(0,listAmountPkr-amountPkr);const purchaseFingerprint=fingerprint({kind:'topup',offerId:offer.id,coins:offer.coins,amountPkr});const key=this.scopedKey({userId,kind:'topup',productId:offer.id,key:idempotencyKey});const prior=this.existing(key,{userId,kind:'topup',purchaseFingerprint});if(prior)return prior;
    const now=this.clock();const transaction={id:randomUUID(),kind:'topup',purpose:'topup',userId,provider:'JazzCash',offerId:offer.id,coins:offer.coins,listAmountPkr,amountPkr,discountPkr,currency:'PKR',status:'pending',providerStatus:'pending',idempotencyKey:key,purchaseFingerprint,createdAt:iso(now),initiatedAt:iso(now),updatedAt:iso(now),attempts:1};const provider=await this.provider.createCheckout({transactionId:transaction.id,referenceType:'topup',referenceId:offer.id,amountPkr,description:`Game Arena ${offer.label}`});Object.assign(transaction,this.safeStoredProvider(provider));this.store.createTransaction(transaction);if(discountPkr>0)this.store.benefitLedger.push({id:randomUUID(),userId,transactionId:transaction.id,type:'member_topup_discount',status:'issued',issuedAmountPkr:discountPkr,redeemedAmountPkr:0,creditedAmountPkr:0,failedAmountPkr:0,reversalRequiredAmountPkr:0,reversedAmountPkr:0,createdAt:iso(now),updatedAt:iso(now)});this.store.audit.write({actor:userId,action:'payment.checkout_created',targetType:'transaction',targetId:transaction.id,metadata:{kind:'topup',offerId:offer.id,coins:offer.coins,listAmountPkr,amountPkr,discountPkr,memberDiscount:isPremium}});return{...transaction,checkout:provider.checkout};
  }
  assertExpected(transaction,event){const expected=transaction.expected||{};const mismatch=[];if(event.billReference!==transaction.id||expected.billReference&&event.billReference!==expected.billReference)mismatch.push('bill_reference');if(!Number.isFinite(event.amountMinor)||event.amountMinor!==Math.round(transaction.amountPkr*100)||expected.amountMinor!==undefined&&event.amountMinor!==expected.amountMinor)mismatch.push('amount');if(event.currency!==(transaction.currency||'PKR')||expected.currency&&event.currency!==expected.currency)mismatch.push('currency');if(expected.merchantId&&event.merchantId!==expected.merchantId)mismatch.push('merchant');if(mismatch.length)throw Object.assign(new Error('Payment notification does not match the stored transaction.'),{status:422,code:'payment_value_mismatch',details:{fields:mismatch}});}
  applyEvent({transactionId,status,providerReference,providerEventId,payload={},signatureValid,event={}}){const transaction=this.store.getTransaction(transactionId);if(!transaction)throw Object.assign(new Error('Unknown transaction.'),{status:404,code:'transaction_not_found'});const recorded=this.store.addPaymentEvent({transactionId,providerEventId,signatureValid,kind:status,providerStatus:status,payload});if(recorded.duplicate)return{transaction,duplicate:true};if(!signatureValid)throw Object.assign(new Error('Invalid payment signature.'),{status:401,code:'invalid_signature'});transaction.providerStatus=status;if(!ALLOWED[transaction.status]?.has(status)){this.store.createReconciliationCase({transactionId,reason:'invalid_transition',expected:transaction.status,received:status});return{transaction,duplicate:false,reconciled:true};}if(transaction.status===status){this.store.saveTransaction(transaction);return{transaction,duplicate:false};}if(status==='paid'){this.assertExpected(transaction,event);this.activate(transaction,providerReference);}else if(status==='failed'||status==='voided'){transaction.status=status;transaction[status==='failed'?'failedAt':'cancelledAt']=iso(this.clock());this.store.saveTransaction(transaction);}else if(status==='refunded')this.refund(transaction.id,{providerReference,reason:'provider_event'});return{transaction:this.store.getTransaction(transaction.id),duplicate:false};}
  activate(transaction,providerReference){transaction.status='paid';transaction.providerStatus='paid';transaction.providerReference=providerReference||transaction.providerReference;transaction.paidAt=iso(this.clock());transaction.completedAt=transaction.paidAt;if(transaction.kind==='topup'){this.store.saveTransaction(transaction);this.store.appendLedger({userId:transaction.userId,amount:transaction.coins,reason:'coin_topup',idempotencyKey:`topup:${transaction.id}`,referenceType:'transaction',referenceId:transaction.id});const benefit=this.store.benefitLedger.find(item=>item.transactionId===transaction.id&&item.type==='member_topup_discount');if(benefit){benefit.status='redeemed';benefit.redeemedAmountPkr=benefit.issuedAmountPkr;benefit.updatedAt=transaction.paidAt;}this.store.audit.write({actor:'system',action:'topup.paid',targetType:'transaction',targetId:transaction.id,metadata:{coins:transaction.coins,providerReference:transaction.providerReference,discountPkr:transaction.discountPkr||0}});return;}const plan=this.plan(transaction.planId);const current=this.store.getEntitlement(transaction.userId,this.clock());const base=current.tier==='premium'&&current.status==='active'&&current.expiresAt>this.clock()?current.expiresAt:this.clock();transaction.entitlementStartsAt=base;transaction.entitlementExpiresAt=base+plan.durationMs;transaction.subscriptionPeriodId=randomUUID();this.store.saveTransaction(transaction);this.store.setEntitlement(transaction.userId,{id:transaction.subscriptionPeriodId,tier:'premium',status:'active',origin:'paid',purpose:transaction.purpose,planId:transaction.planId,planSnapshot:transaction.planSnapshot,sourceType:'payment',sourceId:transaction.id,startsAt:base,currentPeriodStartsAt:base,currentPeriodEndsAt:transaction.entitlementExpiresAt,expiresAt:transaction.entitlementExpiresAt,autoRenew:false});this.store.audit.write({actor:'system',action:'payment.paid',targetType:'transaction',targetId:transaction.id,metadata:{providerReference:transaction.providerReference,purpose:transaction.purpose,subscriptionPeriodId:transaction.subscriptionPeriodId}});}
  recomputeMembership(userId){const valid=[...this.store.transactions.values()].filter(item=>item.userId===userId&&item.kind==='membership'&&item.status==='paid'&&item.entitlementExpiresAt>this.clock()).sort((a,b)=>b.entitlementExpiresAt-a.entitlementExpiresAt);if(valid.length){const source=valid[0];return this.store.setEntitlement(userId,{tier:'premium',status:'active',origin:'paid',purpose:source.purpose,planId:source.planId,planSnapshot:source.planSnapshot,sourceType:'payment-recompute',sourceId:source.id,startsAt:this.clock(),currentPeriodStartsAt:this.clock(),currentPeriodEndsAt:source.entitlementExpiresAt,expiresAt:source.entitlementExpiresAt,autoRenew:false});}return this.store.setEntitlement(userId,{tier:'free',status:'active',origin:'system',sourceType:'refund-recompute',startsAt:this.clock(),expiresAt:null,autoRenew:false});}
  refund(transactionId,{providerReference,reason='refund'}={}){const transaction=this.store.getTransaction(transactionId);if(!transaction||transaction.status!=='paid')throw Object.assign(new Error('Paid transaction not found.'),{status:409,code:'refund_not_allowed'});transaction.status='refunded';transaction.providerStatus='refunded';transaction.refundedAt=iso(this.clock());transaction.refundAmountPkr=transaction.amountPkr;transaction.refundReference=providerReference;this.store.saveTransaction(transaction);if(transaction.kind==='topup'){this.store.appendLedger({userId:transaction.userId,amount:-transaction.coins,reason:'topup_refund',idempotencyKey:`topup-refund:${transaction.id}`,referenceType:'transaction',referenceId:transaction.id});const benefit=this.store.benefitLedger.find(item=>item.transactionId===transaction.id&&item.type==='member_topup_discount');if(benefit){benefit.status='reversed';benefit.reversedAmountPkr=benefit.redeemedAmountPkr;benefit.updatedAt=transaction.refundedAt;}}else this.recomputeMembership(transaction.userId);this.store.audit.write({actor:'system',action:'payment.refunded',targetType:'transaction',targetId:transaction.id,metadata:{reason,kind:transaction.kind||'membership',refundAmountPkr:transaction.refundAmountPkr}});return transaction;}
  reconcile(providerRecords=[]){const seen=new Set();const cases=[];for(const record of providerRecords){seen.add(record.transactionId);const internal=this.store.getTransaction(record.transactionId);if(!internal){cases.push(this.store.createReconciliationCase({transactionId:record.transactionId,reason:'provider_only',providerStatus:record.status}));continue;}if(internal.status!==record.status)cases.push(this.store.createReconciliationCase({transactionId:internal.id,reason:'status_mismatch',internalStatus:internal.status,providerStatus:record.status}));if(record.amountPkr!==undefined&&Number(record.amountPkr)!==internal.amountPkr)cases.push(this.store.createReconciliationCase({transactionId:internal.id,reason:'amount_mismatch',internalAmount:internal.amountPkr,providerAmount:record.amountPkr}));if(record.currency&&record.currency!==internal.currency)cases.push(this.store.createReconciliationCase({transactionId:internal.id,reason:'currency_mismatch',internalCurrency:internal.currency,providerCurrency:record.currency}));}for(const transaction of this.store.transactions.values())if(transaction.status==='pending'&&this.clock()-new Date(transaction.createdAt).getTime()>24*3600000&&!seen.has(transaction.id))cases.push(this.store.createReconciliationCase({transactionId:transaction.id,reason:'stale_pending'}));return cases;}
}
export {PLANS,PLAN_DEFINITIONS,ensureReportingState};
