import {randomUUID} from 'node:crypto';
const PLANS={monthly:{price:299,durationMs:31*86400000},yearly:{price:4999,durationMs:366*86400000}};
const FINAL=new Set(['paid','failed','refunded','voided']);
export class PaymentService{
  constructor({store,provider,clock=()=>Date.now()}){this.store=store;this.provider=provider;this.clock=clock;}
  plan(id){const plan=PLANS[id];if(!plan)throw Object.assign(new Error('Unknown premium plan.'),{status:400,code:'invalid_plan'});return plan;}
  async checkout({userId,planId,idempotencyKey}){const plan=this.plan(planId);const key=idempotencyKey||`checkout:${userId}:${planId}:${Math.floor(this.clock()/300000)}`;const existing=this.store.findTransactionByIdempotency(key);if(existing)return existing;const transaction={id:randomUUID(),kind:'membership',userId,provider:'JazzCash',planId,amountPkr:plan.price,status:'pending',idempotencyKey:key,createdAt:new Date(this.clock()).toISOString(),updatedAt:new Date(this.clock()).toISOString(),attempts:0};const provider=await this.provider.createCheckout({transactionId:transaction.id,referenceType:'membership',referenceId:planId,amountPkr:plan.price,description:`Game Arena+ ${planId}`});Object.assign(transaction,provider);this.store.createTransaction(transaction);this.store.audit.write({actor:userId,action:'payment.checkout_created',targetType:'transaction',targetId:transaction.id,metadata:{kind:'membership',planId,amountPkr:plan.price}});return transaction;}
  async checkoutTopup({userId,offer,idempotencyKey,isPremium=false}){const amountPkr=isPremium?Math.max(1,Math.round(offer.amountPkr*.9)):offer.amountPkr;const key=idempotencyKey||`topup:${userId}:${offer.id}:${Math.floor(this.clock()/300000)}`;const existing=this.store.findTransactionByIdempotency(key);if(existing)return existing;const transaction={id:randomUUID(),kind:'topup',userId,provider:'JazzCash',offerId:offer.id,coins:offer.coins,amountPkr,status:'pending',idempotencyKey:key,createdAt:new Date(this.clock()).toISOString(),updatedAt:new Date(this.clock()).toISOString(),attempts:0};const provider=await this.provider.createCheckout({transactionId:transaction.id,referenceType:'topup',referenceId:offer.id,amountPkr,description:`Game Arena ${offer.label}`});Object.assign(transaction,provider);this.store.createTransaction(transaction);this.store.audit.write({actor:userId,action:'payment.checkout_created',targetType:'transaction',targetId:transaction.id,metadata:{kind:'topup',offerId:offer.id,coins:offer.coins,amountPkr,memberDiscount:isPremium}});return transaction;}
  applyEvent({transactionId,status,providerReference,providerEventId,payload={},signatureValid}){const transaction=this.store.getTransaction(transactionId);if(!transaction)throw Object.assign(new Error('Unknown transaction.'),{status:404,code:'transaction_not_found'});const event=this.store.addPaymentEvent({transactionId,providerEventId,signatureValid,kind:status,payload});if(event.duplicate)return{transaction,duplicate:true};if(!signatureValid)throw Object.assign(new Error('Invalid payment signature.'),{status:401,code:'invalid_signature'});if(FINAL.has(transaction.status)){if(transaction.status!==status)this.store.createReconciliationCase({transactionId,reason:'out_of_order_final_event',expected:transaction.status,received:status});return{transaction,duplicate:false};}if(status==='paid')this.activate(transaction,providerReference);else if(status==='failed'||status==='voided'){transaction.status=status;this.store.saveTransaction(transaction);}else transaction.status='pending';return{transaction:this.store.getTransaction(transaction.id),duplicate:false};}
  activate(transaction,providerReference){transaction.status='paid';transaction.providerReference=providerReference||transaction.providerReference;transaction.paidAt=new Date(this.clock()).toISOString();this.store.saveTransaction(transaction);if(transaction.kind==='topup'){this.store.appendLedger({userId:transaction.userId,amount:transaction.coins,reason:'coin_topup',idempotencyKey:`topup:${transaction.id}`,referenceType:'transaction',referenceId:transaction.id});this.store.audit.write({actor:'system',action:'topup.paid',targetType:'transaction',targetId:transaction.id,metadata:{coins:transaction.coins,providerReference:transaction.providerReference}});return;}const plan=this.plan(transaction.planId);const current=this.store.getEntitlement(transaction.userId,this.clock());const base=current.tier==='premium'&&current.status==='active'&&current.expiresAt>this.clock()?current.expiresAt:this.clock();this.store.setEntitlement(transaction.userId,{tier:'premium',status:'active',sourceType:'payment',sourceId:transaction.id,startsAt:this.clock(),expiresAt:base+plan.durationMs});this.store.audit.write({actor:'system',action:'payment.paid',targetType:'transaction',targetId:transaction.id,metadata:{providerReference:transaction.providerReference}});}
  refund(transactionId,{providerReference,reason='refund'}={}){const transaction=this.store.getTransaction(transactionId);if(!transaction||transaction.status!=='paid')throw Object.assign(new Error('Paid transaction not found.'),{status:409,code:'refund_not_allowed'});transaction.status='refunded';transaction.refundedAt=new Date(this.clock()).toISOString();transaction.refundReference=providerReference;this.store.saveTransaction(transaction);if(transaction.kind==='topup')this.store.appendLedger({userId:transaction.userId,amount:-transaction.coins,reason:'topup_refund',idempotencyKey:`topup-refund:${transaction.id}`,referenceType:'transaction',referenceId:transaction.id});else this.store.setEntitlement(transaction.userId,{tier:'free',status:'refunded',sourceType:'refund',sourceId:transaction.id,startsAt:this.clock(),expiresAt:this.clock()});this.store.audit.write({actor:'system',action:'payment.refunded',targetType:'transaction',targetId:transaction.id,metadata:{reason,kind:transaction.kind||'membership'}});return transaction;}
  reconcile(providerRecords=[]){const seen=new Set();const cases=[];for(const record of providerRecords){seen.add(record.transactionId);const internal=this.store.getTransaction(record.transactionId);if(!internal){cases.push(this.store.createReconciliationCase({transactionId:record.transactionId,reason:'provider_only',providerStatus:record.status}));continue;}if(internal.status!==record.status)cases.push(this.store.createReconciliationCase({transactionId:internal.id,reason:'status_mismatch',internalStatus:internal.status,providerStatus:record.status}));if(record.amountPkr!==undefined&&Number(record.amountPkr)!==internal.amountPkr)cases.push(this.store.createReconciliationCase({transactionId:internal.id,reason:'amount_mismatch',internalAmount:internal.amountPkr,providerAmount:record.amountPkr}));}for(const transaction of this.store.transactions.values())if(transaction.status==='pending'&&this.clock()-new Date(transaction.createdAt).getTime()>24*3600000&&!seen.has(transaction.id))cases.push(this.store.createReconciliationCase({transactionId:transaction.id,reason:'stale_pending'}));return cases;}
}
export {PLANS};
