import {randomUUID} from 'node:crypto';
import {corsHeaders,readJson,send} from './lib/http.mjs';
import {requestIp,sha256} from './lib/security.mjs';
import {authenticateAdmin} from './lib/admin-auth.mjs';
import {SubscriptionReportService,capabilitiesFor,parseReportFilters,requireCapability} from './services/subscription-reports.mjs';

const ANALYTICS=new Set(['route_view','game_impression','game_play_intent','game_start','game_exit','game_complete','upgrade_view','plan_select','checkout_start','checkout_complete','otp_request','otp_complete','account_export','setting_change','web_vital','frontend_error']);
const SENSITIVE=/(phone|email|otp|token|secret|payment|identifier|session|cnic|address)/i;
const fail=(message,status=400,code='invalid_request')=>Object.assign(new Error(message),{status,code});
const DAY_MS=86400000;
function sendCsv(res,result,cors){res.writeHead(200,{...cors,'content-type':result.contentType,'content-disposition':`attachment; filename="${result.filename}"`,'cache-control':'no-store','x-report-schema-version':result.audit.schemaVersion,'x-report-row-count':String(result.rowCount)});res.end(result.body);}
function currentPlan(store,id){return store.planVersions.find(item=>item.id===id);}

export function createSupplementalApp({config,store}){
  const admin=(req,roles)=>authenticateAdmin(req,config,roles);
  const reports=new SubscriptionReportService({store});
  return async function supplemental(req,res){
    const url=new URL(req.url,'http://localhost');const path=url.pathname;const method=req.method||'GET';const cors=corsHeaders(req.headers.origin,config.allowedOrigins);const reply=(status,payload,headers={})=>send(res,status,payload,{...cors,...headers});
    if(method==='POST'&&path==='/v1/events'){
      try{const ipHash=sha256(requestIp(req));if(store.hitRateLimit(`analytics:${ipHash}`,120,60000))throw fail('Too many events.',429,'rate_limited');const {value}=await readJson(req,8192);if(!ANALYTICS.has(value.name))throw fail('Unsupported analytics event.',400,'invalid_event');const properties=Object.fromEntries(Object.entries(value.properties||{}).filter(([key,item])=>!SENSITIVE.test(key)&&['string','number','boolean'].includes(typeof item)).slice(0,20));store.metrics.increment('analytics_events_total',{name:value.name});if(value.name==='web_vital'&&Number.isFinite(Number(properties.value)))store.metrics.observe(`web_vital_${String(properties.metric||'unknown').replace(/[^a-z0-9_-]/gi,'_')}`,Number(properties.value));return reply(202,{accepted:true,eventId:randomUUID()});}catch(error){return reply(error.status||400,{error:{code:error.code||'invalid_event',message:error.message}});}
    }
    if(!path.startsWith('/v1/admin/'))return false;
    try{
      if(method==='GET'&&path==='/v1/admin/capabilities'){const principal=admin(req,['any']);return reply(200,{actor:principal.actor,role:principal.role,roles:principal.roles,capabilities:capabilitiesFor(principal.roles)});}
      if(method==='GET'&&path==='/v1/admin/plans'){const principal=admin(req,['admin','finance','support','operator']);requireCapability(principal,'subscription.read');return reply(200,{plans:reports.plans(),billingMode:'single',currency:'PKR',recurringBilling:false});}
      const planMatch=path.match(/^\/v1\/admin\/plans\/([a-z0-9-]+)$/);
      if(method==='PATCH'&&planMatch){const principal=admin(req,['admin']);requireCapability(principal,'subscription.manage_plans');const {value}=await readJson(req);if(!value.reason)throw fail('A reason is required.',400,'reason_required');const plan=currentPlan(store,planMatch[1]);if(!plan)throw fail('Plan not found.',404,'plan_not_found');const action=String(value.action||'');if(!['activate','retire','schedule'].includes(action))throw fail('Unsupported plan action.',400,'invalid_plan_action');if(action==='activate'){plan.status='active';plan.effectiveAt=new Date().toISOString();plan.retiredAt=null;plan.scheduledAt=null;}else if(action==='retire'){plan.status='retired';plan.retiredAt=new Date().toISOString();}else{const scheduled=Date.parse(value.scheduledAt);if(!Number.isFinite(scheduled)||scheduled<=Date.now())throw fail('A future scheduledAt value is required.',400,'invalid_schedule');plan.status='scheduled';plan.scheduledAt=new Date(scheduled).toISOString();}store.markDirty?.();store.audit.write({actor:principal.actor,action:`subscription.plan_${action}`,targetType:'plan',targetId:plan.id,metadata:{reason:value.reason,version:plan.version,scheduledAt:plan.scheduledAt}});return reply(200,{plan});}
      const adjustMatch=path.match(/^\/v1\/admin\/subscriptions\/([a-f0-9-]+)\/adjust$/);
      if(method==='POST'&&adjustMatch){const principal=admin(req,['admin','finance']);requireCapability(principal,'subscription.adjust');const {value}=await readJson(req);if(!value.reason)throw fail('A reason is required.',400,'reason_required');const user=store.getUser(adjustMatch[1]);if(!user)throw fail('User not found.',404,'user_not_found');const action=String(value.action||'');const now=Date.now();const current=store.getEntitlement(user.id,now);if(action==='grant'||action==='extend'){const durationDays=Number(value.durationDays);if(!Number.isInteger(durationDays)||durationDays<1||durationDays>3660)throw fail('durationDays must be between 1 and 3660.',400,'invalid_duration');const base=action==='extend'&&current.tier==='premium'&&current.status==='active'&&current.expiresAt>now?current.expiresAt:now;const planId=String(value.planId||current.planId||'manual');const plan=currentPlan(store,planId);const entitlement=store.setEntitlement(user.id,{tier:'premium',status:'active',origin:'manual_grant',purpose:action==='extend'?'manual_extension':'manual_grant',planId,planSnapshot:plan?structuredClone(plan):{id:planId,name:'Audited temporary access',billingMode:'manual'},sourceType:action==='extend'?'manual_extension':'manual_grant',sourceId:randomUUID(),startsAt:base,currentPeriodStartsAt:base,currentPeriodEndsAt:base+durationDays*DAY_MS,expiresAt:base+durationDays*DAY_MS,autoRenew:false,adjustedBy:principal.actor,adjustmentReason:value.reason});store.audit.write({actor:principal.actor,action:`subscription.${action}`,targetType:'user',targetId:user.id,metadata:{reason:value.reason,durationDays,planId,entitlementId:entitlement.id}});return reply(200,{entitlement});}if(action==='revoke'){if(current.tier==='premium')store.setEntitlement(user.id,{...current,id:randomUUID(),status:'cancelled',cancelledAt:now,sourceType:'manual_revoke',origin:current.origin||'manual_grant',adjustedBy:principal.actor,adjustmentReason:value.reason});const entitlement=store.setEntitlement(user.id,{tier:'free',status:'active',origin:'system',sourceType:'manual_revoke',sourceId:randomUUID(),startsAt:now,expiresAt:null,autoRenew:false});store.audit.write({actor:principal.actor,action:'subscription.revoke',targetType:'user',targetId:user.id,metadata:{reason:value.reason,priorEntitlementId:current.id}});return reply(200,{entitlement});}throw fail('Unsupported subscription adjustment.',400,'invalid_subscription_action');}
      const subscriptionDetail=path.match(/^\/v1\/admin\/subscriptions\/([a-f0-9-]+)$/);
      if(method==='GET'&&subscriptionDetail){const principal=admin(req,['admin','finance','support','operator']);requireCapability(principal,'subscription.read');const user=store.getUser(subscriptionDetail[1]);if(!user)throw fail('User not found.',404,'user_not_found');const params=new URLSearchParams(url.searchParams);params.set('q',user.id);params.set('limit','200');const filters=parseReportFilters(params);const ledger=reports.subscriptionLedger(filters);return reply(200,{user:{id:user.id,displayName:user.displayName,status:user.status},current:store.getEntitlement(user.id),history:ledger.rows});}
      if(method==='GET'&&path==='/v1/admin/payments'){const principal=admin(req,['admin','finance','support']);requireCapability(principal,'reports.read');const filters=parseReportFilters(url.searchParams);const ledger=reports.paymentLedger(filters);const reconciliation=reports.reconciliation({...filters,cursor:0,limit:Math.min(filters.limit,100)});return reply(200,{schemaVersion:ledger.schemaVersion,timeZone:ledger.timeZone,effectiveRange:ledger.effectiveRange,transactions:ledger.rows,reconciliationCases:reconciliation.rows,page:ledger.page});}
      if(method==='GET'&&path==='/v1/admin/reports/subscriptions/summary'){const principal=admin(req,['admin','finance','support','operator','security']);requireCapability(principal,'reports.read');return reply(200,reports.summary(parseReportFilters(url.searchParams)));}
      if(method==='GET'&&path==='/v1/admin/reports/payments'){const principal=admin(req,['admin','finance','support','operator']);requireCapability(principal,'reports.read');return reply(200,reports.paymentLedger(parseReportFilters(url.searchParams)));}
      if(method==='GET'&&path==='/v1/admin/reports/subscriptions'){const principal=admin(req,['admin','finance','support','operator']);requireCapability(principal,'reports.read');return reply(200,reports.subscriptionLedger(parseReportFilters(url.searchParams)));}
      if(method==='GET'&&path==='/v1/admin/reports/recurring-customers'){const principal=admin(req,['admin','finance','support','operator']);requireCapability(principal,'reports.read');return reply(200,reports.recurringCustomers(parseReportFilters(url.searchParams)));}
      if(method==='GET'&&path==='/v1/admin/reports/reconciliation'){const principal=admin(req,['admin','finance','support','operator']);requireCapability(principal,'reports.read');return reply(200,reports.reconciliation(parseReportFilters(url.searchParams)));}
      if(method==='GET'&&path==='/v1/admin/reports/benefit-costs'){const principal=admin(req,['admin','finance','support','operator']);requireCapability(principal,'reports.read');return reply(200,reports.benefitCosts(parseReportFilters(url.searchParams)));}
      if(method==='GET'&&path==='/v1/admin/reports/exports'){const principal=admin(req,['admin','finance']);requireCapability(principal,'reports.export');return reply(200,reports.exportHistory(parseReportFilters(url.searchParams)));}
      const exportMatch=path.match(/^\/v1\/admin\/reports\/exports\/(summary|payments|subscriptions|recurring-customers|reconciliation|benefit-costs)$/);
      if(method==='GET'&&exportMatch){const principal=admin(req,['admin','finance']);requireCapability(principal,'reports.export');return sendCsv(res,reports.export(exportMatch[1],parseReportFilters(url.searchParams),principal),cors);}
      if(method==='GET'&&path==='/v1/admin/games'){admin(req,['admin','operator','support','security']);return reply(200,{games:store.games.map(game=>({...game,state:game.status,versions:[{version:game.version||'external',gameUrl:game.gameUrl,status:game.status}]})),reports:[]});}
      if(method==='GET'&&path==='/v1/admin/reviews'){admin(req,['admin','operator','support','security','finance']);return reply(200,{results:store.scoreEvents.filter(item=>item.status==='review'||item.status==='rejected').slice(-500),adjustments:[...store.adjustments.values()].filter(item=>item.status==='pending_approval'),reconciliationCases:reports.reconciliation(parseReportFilters(new URLSearchParams('preset=last30&limit=100'))).rows});}
      return false;
    }catch(error){reply(error.status||500,{error:{code:error.code||'internal_error',message:error.status>=500?'Unexpected server error.':error.message,details:error.details}});return true;}
  };
}
