import {randomUUID} from 'node:crypto';
import {readJson,readPayload,send,problem,redirect,corsHeaders} from './lib/http.mjs';
import {assertCsrf,clearCookie,csrfCookie,deviceFingerprint,normalizeIdentifier,parseCookies,randomToken,requestIp,safeEqual,sessionCookie,sha256,sixDigitCode} from './lib/security.mjs';
import {MockOtpProvider,OtpDeliveryRouter} from './adapters/otp-delivery.mjs';
import {PaymentService} from './services/payments.mjs';
import {RewardPolicy} from './services/reward-policy.mjs';
import {CatalogueAdmin} from './services/catalogue-admin.mjs';

const fail=(message,status=400,code='invalid_request',details)=>Object.assign(new Error(message),{status,code,details});
const dayStart=now=>now-now%86400000;
const maskIdentity=item=>item.type==='phone'?`${item.value.slice(0,4)}******${item.value.slice(-2)}`:item.value.replace(/^(.).+(@.+)$/,'$1***$2');

export function createApp({config,store,jazzcash,otpDelivery,payments,rewardPolicy,catalogueAdmin,clock=()=>Date.now()}){
  const delivery=otpDelivery??new OtpDeliveryRouter({providers:[new MockOtpProvider()],audit:store.audit,metrics:store.metrics});
  const paymentService=payments??new PaymentService({store,provider:jazzcash,clock});
  const rewards=rewardPolicy??new RewardPolicy({config,store,clock});
  const gameAdmin=catalogueAdmin??new CatalogueAdmin(store.games);
  const secure=config.nodeEnv==='production';
  function authContext(req){const cookies=parseCookies(req.headers.cookie);const token=cookies[config.sessionCookieName];if(!token)return null;const hash=sha256(token);const session=store.getSession(hash);if(!session)return null;const user=store.getUser(session.userId);return user?{user,session,hash,cookies}:null;}
  function requireUser(req){const context=authContext(req);if(!context)throw fail('Sign in is required.',401,'authentication_required');return context;}
  function mutation(req){assertCsrf(req,config);const origin=req.headers.origin;if(origin&&config.allowedOrigins.length&&!config.allowedOrigins.includes(origin))throw fail('Origin is not allowed.',403,'origin_rejected');}
  function requireAdmin(req,roles=['admin']){const key=String(req.headers['x-admin-key']||'');if(!key||!config.adminApiKeys.some(candidate=>safeEqual(candidate,key)))throw fail('Administrative authentication required.',401,'admin_authentication_required');const role=String(req.headers['x-admin-role']||'admin');if(!roles.includes(role)&&!roles.includes('any'))throw fail('Administrative role is not permitted.',403,'admin_forbidden');return{actor:`admin:${sha256(key).slice(0,12)}`,role};}
  return async function handler(req,res){
    const started=clock();const requestId=String(req.headers['x-request-id']||randomUUID()).slice(0,80);res.setHeader('x-request-id',requestId);const origin=req.headers.origin;const cors=corsHeaders(origin,config.allowedOrigins);
    const reply=(status,payload,headers={})=>send(res,status,payload,{...cors,...headers});
    try{
      const url=new URL(req.url,'http://localhost');const path=url.pathname;const method=req.method??'GET';
      if(method==='OPTIONS'&&origin&&config.allowedOrigins.includes(origin))return reply(204,null,{'access-control-allow-methods':'GET,POST,PATCH,DELETE,OPTIONS','access-control-allow-headers':'content-type,x-csrf-token,x-request-id,idempotency-key,x-device-id','access-control-max-age':'600'});
      if(method==='GET'&&path==='/healthz')return reply(200,{status:'ok',service:'game-arena-api',time:new Date(clock()).toISOString()});
      if(method==='GET'&&path==='/readyz')return reply(200,{status:'ready',catalogue:store.listGames().length,payments:config.jazzcashMode,otp:config.otpProviderMode});
      if(method==='GET'&&path==='/v1/catalog/games')return reply(200,{games:store.listGames().map(({source,qaNote,...game})=>game)},{'cache-control':'public, max-age=30, stale-while-revalidate=120'});
      const gameMatch=path.match(/^\/v1\/catalog\/games\/([a-z0-9-]+)$/);if(method==='GET'&&gameMatch){const game=store.getGame(gameMatch[1]);if(!game)throw fail('Game not found.',404,'game_not_found');return reply(200,{game});}

      if(method==='POST'&&path==='/v1/auth/otp'){
        const {value}=await readJson(req);const identity=normalizeIdentifier(value.identifier);const ipHash=sha256(requestIp(req));const deviceHash=deviceFingerprint(req);const now=clock();
        const recent=[...store.otp.values()].find(item=>item.identity.type===identity.type&&item.identity.value===identity.value&&!item.consumed&&item.createdAt>now-config.otpResendSeconds*1000);if(recent)throw fail('Please wait before requesting another code.',429,'otp_resend_too_soon',{retryAfter:Math.ceil((recent.createdAt+config.otpResendSeconds*1000-now)/1000)});
        if(store.hitRateLimit(`otp:identity:${sha256(identity.value)}`,config.otpAccountLimit,15*60*1000,now)||store.hitRateLimit(`otp:ip:${ipHash}`,config.otpIpLimit,15*60*1000,now)||store.hitRateLimit(`otp:device:${deviceHash}`,config.otpDeviceLimit,15*60*1000,now))throw fail('Too many verification requests. Try again later.',429,'rate_limited');
        const code=sixDigitCode();const challenge={id:randomUUID(),identity,codeHash:sha256(code),expiresAt:now+config.otpTtlSeconds*1000,createdAt:now,attempts:0,consumed:false,ipHash,deviceHash};store.createOtp(challenge);const delivered=await delivery.send({identity,code,templateId:'game-arena-login'});store.audit.write({actor:'anonymous',action:'otp.requested',targetType:'identity',targetId:sha256(identity.value).slice(0,16),requestId,metadata:{channel:identity.type,provider:delivered.provider}});store.metrics.increment('otp_requests_total',{channel:identity.type});
        return reply(202,{challengeId:challenge.id,expiresIn:config.otpTtlSeconds,resendIn:config.otpResendSeconds,...(config.allowDebugOtp?{debugCode:code}:{})});
      }
      if(method==='POST'&&path==='/v1/auth/otp/verify'){
        const {value}=await readJson(req);const challenge=store.getOtp(value.challengeId);const now=clock();if(!challenge||challenge.expiresAt<now||challenge.consumed)throw fail('Verification code is invalid or expired.',400,'invalid_otp');
        challenge.attempts+=1;if(challenge.attempts>config.otpMaxAttempts){store.saveOtp(challenge);throw fail('Too many attempts. Request a new code.',429,'otp_attempts_exceeded');}
        if(!/^\d{6}$/.test(String(value.code??''))||!safeEqual(challenge.codeHash,sha256(value.code))){store.saveOtp(challenge);store.metrics.increment('otp_verifications_total',{status:'failed'});throw fail('Verification code is invalid or expired.',400,'invalid_otp');}
        challenge.consumed=true;challenge.consumedAt=now;store.saveOtp(challenge);const user=store.findOrCreateUser(challenge.identity);const token=randomToken();const csrf=randomToken(18);const deviceHash=deviceFingerprint(req);const ipHash=sha256(requestIp(req));const known=store.devices.has(`${user.id}:${deviceHash}`);const session={id:randomUUID(),hash:sha256(token),csrfHash:sha256(csrf),userId:user.id,deviceHash,ipHash,risk:known?'normal':'new_device',createdAt:now,lastSeenAt:now,rotatedAt:now,expiresAt:now+config.sessionTtlSeconds*1000,revokedAt:null};store.createSession(session);store.audit.write({actor:user.id,action:'auth.signed_in',targetType:'session',targetId:session.id,requestId,metadata:{identityType:challenge.identity.type,risk:session.risk}});store.metrics.increment('otp_verifications_total',{status:'success'});
        return reply(200,{user,entitlement:store.getEntitlement(user.id).tier,coins:store.wallet(user.id),csrfToken:csrf},{'set-cookie':[sessionCookie(config.sessionCookieName,token,config.sessionTtlSeconds,secure),csrfCookie(config.csrfCookieName,csrf,config.sessionTtlSeconds,secure)]});
      }
      if(method==='GET'&&path==='/v1/session'){
        const context=authContext(req);if(!context)return reply(200,{authenticated:false});let headers={};let csrfToken;
        if(clock()-context.session.rotatedAt>config.sessionRotationSeconds*1000){const token=randomToken();csrfToken=randomToken(18);const previous=context.hash;context.session.hash=sha256(token);context.session.csrfHash=sha256(csrfToken);context.session.rotatedAt=clock();store.saveSession(previous,context.session);headers={'set-cookie':[sessionCookie(config.sessionCookieName,token,config.sessionTtlSeconds,secure),csrfCookie(config.csrfCookieName,csrfToken,config.sessionTtlSeconds,secure)]};store.audit.write({actor:context.user.id,action:'session.rotated',targetType:'session',targetId:context.session.id,requestId});}
        return reply(200,{authenticated:true,user:context.user,entitlement:store.getEntitlement(context.user.id),coins:store.wallet(context.user.id),sessions:store.listSessions(context.user.id),...(csrfToken?{csrfToken}:{})},headers);
      }
      if(method==='POST'&&path==='/v1/auth/logout'){const context=authContext(req);if(context){mutation(req);store.deleteSession(context.hash);}return reply(204,null,{'set-cookie':[clearCookie(config.sessionCookieName,secure),clearCookie(config.csrfCookieName,secure,false)]});}
      if(method==='POST'&&path==='/v1/auth/logout-all'){const {user,hash}=requireUser(req);mutation(req);const revoked=store.revokeUserSessions(user.id,{exceptHash:hash});return reply(200,{revoked});}
      if(method==='GET'&&path==='/v1/account/sessions'){const {user}=requireUser(req);return reply(200,{sessions:store.listSessions(user.id)});}
      const revokeSession=path.match(/^\/v1\/account\/sessions\/([a-f0-9-]+)$/);if(method==='DELETE'&&revokeSession){const {user}=requireUser(req);mutation(req);const target=[...store.sessions.entries()].find(([,item])=>item.id===revokeSession[1]&&item.userId===user.id);if(!target)throw fail('Session not found.',404,'session_not_found');store.deleteSession(target[0],'user_revoked');return reply(204,null);}
      if(method==='GET'&&path==='/v1/account/export'){const {user}=requireUser(req);return reply(200,store.exportAccount(user.id),{'content-disposition':'attachment; filename="game-arena-account.json"'});}
      if(method==='DELETE'&&path==='/v1/account'){const {user}=requireUser(req);mutation(req);store.requestDeletion(user.id,clock());return reply(202,{status:'deletion_pending',retentionDays:config.retentionDays},{'set-cookie':[clearCookie(config.sessionCookieName,secure),clearCookie(config.csrfCookieName,secure,false)]});}
      if(method==='GET'&&path==='/v1/entitlements/me'){const {user}=requireUser(req);const entitlement=store.getEntitlement(user.id,clock());return reply(200,{entitlement:entitlement.tier,status:entitlement.status,expiresAt:entitlement.expiresAt,history:store.entitlementTimeline(user.id)});}

      if(method==='POST'&&path==='/v1/payments/jazzcash/checkout'){const {user}=requireUser(req);mutation(req);const {value}=await readJson(req);const transaction=await paymentService.checkout({userId:user.id,planId:value.planId,idempotencyKey:req.headers['idempotency-key']});return reply(201,{transactionId:transaction.id,status:transaction.status,provider:'JazzCash',checkout:transaction.checkout,redirectUrl:transaction.checkout?.redirectUrl});}
      const paymentStatus=path.match(/^\/v1\/payments\/([a-f0-9-]+)$/);if(method==='GET'&&paymentStatus){const {user}=requireUser(req);const transaction=store.getTransaction(paymentStatus[1]);if(!transaction||transaction.userId!==user.id)throw fail('Transaction not found.',404,'transaction_not_found');return reply(200,{transactionId:transaction.id,status:transaction.status,planId:transaction.planId,amountPkr:transaction.amountPkr,entitlement:store.getEntitlement(user.id,clock())});}
      if(method==='POST'&&(path==='/v1/payments/jazzcash/webhook'||path==='/v1/payments/jazzcash/return')){const {value,raw}=await readPayload(req,65536);const valid=jazzcash.verifyWebhook(raw,req.headers['x-jazzcash-signature'],value);const transactionId=value.transactionId||value.pp_BillReference;const status=value.status||jazzcash.mapStatus(value);const providerReference=value.providerReference||value.pp_RetreivalReferenceNo||value.pp_TxnRefNo;const providerEventId=value.providerEventId||`${transactionId}:${providerReference||''}:${value.pp_ResponseCode||status}`;const result=paymentService.applyEvent({transactionId,status,providerReference,providerEventId,payload:value,signatureValid:valid});store.metrics.increment('payment_events_total',{status:result.transaction.status});if(path.endsWith('/return'))return redirect(res,303,`${config.publicOrigin}/#/payment-return?transactionId=${encodeURIComponent(transactionId)}&status=${encodeURIComponent(result.transaction.status)}`);return reply(202,{accepted:true,duplicate:result.duplicate});}

      if(method==='GET'&&path==='/v1/wallet'){const {user}=requireUser(req);return reply(200,{balance:store.wallet(user.id),currency:'Arena Coins',entries:store.walletEntries(user.id,{limit:Number(url.searchParams.get('limit'))||50})});}
      if(method==='POST'&&path==='/v1/play-sessions'){const {user}=requireUser(req);mutation(req);const {value}=await readJson(req);const game=store.getGame(value.gameId);if(!game)throw fail('Game not found.',404,'game_not_found');const entitlement=store.getEntitlement(user.id,clock());if(game.tier==='premium'&&!(entitlement.tier==='premium'&&entitlement.status==='active'))throw fail('Game Arena+ is required.',403,'premium_required');const session=store.createPlaySession({id:randomUUID(),userId:user.id,gameId:game.id,gameVersion:game.version||'external',startedAt:clock(),status:'active',nonce:randomToken(12)});store.metrics.increment('game_starts_total',{gameId:game.id,tier:game.tier});return reply(201,{playSessionId:session.id,gameVersion:session.gameVersion,nonce:session.nonce});}
      const completion=path.match(/^\/v1\/play-sessions\/([^/]+)\/complete$/);if(method==='POST'&&completion){const {user}=requireUser(req);mutation(req);const {value}=await readJson(req);const session=store.getPlaySession(completion[1]);if(!session||session.userId!==user.id)throw fail('Play session not found.',404,'play_session_not_found');if(session.status==='completed')return reply(200,{accepted:true,reward:session.reward,balance:store.wallet(user.id),idempotent:true,status:'verified'});if(session.status==='review')return reply(202,{accepted:false,reward:0,balance:store.wallet(user.id),idempotent:true,status:'review'});if(value.nonce&&value.nonce!==session.nonce)throw fail('Play session proof is invalid.',422,'result_rejected');const game=store.getGame(session.gameId);const validation=rewards.validate({user,game,session,score:value.score,durationMs:value.durationMs,clientCompletedAt:value.completedAt,gameVersion:value.gameVersion});session.completedAt=clock();session.score=validation.score;session.durationMs=validation.durationMs;session.status=validation.status==='verified'?'completed':'review';store.savePlaySession(session);store.addScore({playSessionId:session.id,userId:user.id,gameId:game.id,gameVersion:session.gameVersion,score:validation.score,durationMs:validation.durationMs,completedAt:session.completedAt,status:validation.status,reasons:validation.reasons});const decision=rewards.reward({user,game,session,validation});session.reward=decision.reward;store.savePlaySession(session);store.metrics.increment('game_results_total',{gameId:game.id,status:validation.status});return reply(validation.accepted?200:202,{accepted:validation.accepted,reward:decision.reward,balance:store.wallet(user.id),idempotent:false,status:validation.status,...(!validation.accepted?{reviewReference:session.id}:{})});}
      const leaderboard=path.match(/^\/v1\/leaderboards\/([a-z0-9-]+)$/);if(method==='GET'&&leaderboard)return reply(200,{gameId:leaderboard[1],entries:store.leaderboard(leaderboard[1],{limit:Math.min(Number(url.searchParams.get('limit'))||100,100)})},{'cache-control':'public, max-age=30'});
      if(method==='GET'&&path==='/v1/challenges'){const context=authContext(req);const challenges=[...store.challenges.values()].filter(item=>item.status==='live').map(item=>({...item,progress:context?store.challengeProgress(context.user.id,item.id):null}));return reply(200,{challenges});}
      const claim=path.match(/^\/v1\/challenges\/([a-z0-9-]+)\/claim$/);if(method==='POST'&&claim){const {user}=requireUser(req);mutation(req);const challenge=store.challenges.get(claim[1]);if(!challenge)throw fail('Challenge not found.',404,'challenge_not_found');const entitlement=store.getEntitlement(user.id,clock());if(challenge.premium&&entitlement.tier!=='premium')throw fail('Game Arena+ is required.',403,'premium_required');const progress=store.challengeProgress(user.id,challenge.id);if(!progress.complete)throw fail('Challenge is not complete.',409,'challenge_incomplete');const entry=store.appendLedger({userId:user.id,amount:challenge.reward,reason:'challenge_reward',idempotencyKey:`challenge:${challenge.id}:${user.id}`,referenceType:'challenge',referenceId:challenge.id});return reply(200,{reward:entry.amount,balance:store.wallet(user.id),idempotent:Boolean(entry.duplicate)});}
      if(method==='GET'&&path==='/v1/tournaments')return reply(200,{tournaments:[...store.tournaments.values()]},{'cache-control':'public, max-age=30'});
      const join=path.match(/^\/v1\/tournaments\/([a-z0-9-]+)\/join$/);if(method==='POST'&&join){const {user}=requireUser(req);mutation(req);const tournament=store.tournaments.get(join[1]);if(!tournament)throw fail('Tournament not found.',404,'tournament_not_found');const entitlement=store.getEntitlement(user.id,clock());if(tournament.premium&&entitlement.tier!=='premium')throw fail('Game Arena+ is required.',403,'premium_required');if(tournament.status!=='open'||clock()<tournament.startsAt||clock()>tournament.endsAt)throw fail('Tournament entry is closed.',409,'tournament_closed');return reply(201,{entry:store.joinTournament(user.id,tournament.id)});}

      if(path.startsWith('/v1/admin/')){
        if(method==='GET'&&path==='/v1/admin/metrics'){requireAdmin(req,['admin','security','operator']);return reply(200,store.metrics.snapshot());}
        if(method==='GET'&&path==='/v1/admin/audit'){requireAdmin(req,['admin','security','operator','finance','support']);return reply(200,{events:store.audit.search({actor:url.searchParams.get('actor')||undefined,action:url.searchParams.get('action')||undefined,targetType:url.searchParams.get('targetType')||undefined,targetId:url.searchParams.get('targetId')||undefined,limit:Number(url.searchParams.get('limit'))||100})});}
        if(method==='GET'&&path==='/v1/admin/users'){requireAdmin(req,['admin','support','security']);const query=String(url.searchParams.get('q')||'').toLowerCase();const users=[...store.users.values()].filter(item=>!query||item.id.includes(query)||item.displayName.toLowerCase().includes(query)).slice(0,100).map(user=>({id:user.id,displayName:user.displayName,status:user.status,createdAt:user.createdAt,identities:[...store.identities.values()].filter(item=>item.userId===user.id).map(item=>({type:item.type,value:maskIdentity(item)})),entitlement:store.getEntitlement(user.id),coins:store.wallet(user.id)}));return reply(200,{users});}
        if(method==='GET'&&path==='/v1/admin/payments'){requireAdmin(req,['admin','finance','support']);return reply(200,{transactions:[...store.transactions.values()].slice(-500),reconciliationCases:store.reconciliationCases.slice(-500)});}
        if(method==='POST'&&path==='/v1/admin/payments/reconcile'){const admin=requireAdmin(req,['admin','finance']);const {value}=await readJson(req,1048576);const cases=paymentService.reconcile(value.records||[]);store.audit.write({actor:admin.actor,action:'payment.reconciliation_run',targetType:'payment_batch',targetId:randomUUID(),requestId,metadata:{records:value.records?.length||0,cases:cases.length}});return reply(200,{cases});}
        const refund=path.match(/^\/v1\/admin\/payments\/([a-f0-9-]+)\/refund$/);if(method==='POST'&&refund){const admin=requireAdmin(req,['admin','finance']);const {value}=await readJson(req);const transaction=paymentService.refund(refund[1],{providerReference:value.providerReference,reason:value.reason});store.audit.write({actor:admin.actor,action:'payment.refund_recorded',targetType:'transaction',targetId:transaction.id,requestId});return reply(200,{transaction});}
        const gameState=path.match(/^\/v1\/admin\/games\/([a-z0-9-]+)\/state$/);if(method==='POST'&&gameState){const admin=requireAdmin(req,['admin','operator']);const {value}=await readJson(req);const game=gameAdmin.transition(gameState[1],value.state,{actor:admin.actor,reason:value.reason,scheduledAt:value.scheduledAt});store.saveGame({...store.games.find(item=>item.id===game.id),...game,status:game.state});return reply(200,{game});}
        const gameEdit=path.match(/^\/v1\/admin\/games\/([a-z0-9-]+)$/);if(method==='PATCH'&&gameEdit){const admin=requireAdmin(req,['admin','operator']);const {value}=await readJson(req);const game=gameAdmin.edit(gameEdit[1],value.patch,{actor:admin.actor,reason:value.reason});store.saveGame({...store.games.find(item=>item.id===game.id),...game,status:game.state});return reply(200,{game});}
        if(method==='POST'&&path==='/v1/admin/coins/adjustments'){const admin=requireAdmin(req,['admin','support','finance']);const {value}=await readJson(req);const amount=Number(value.amount);if(!Number.isInteger(amount)||amount===0)throw fail('Adjustment amount must be a non-zero integer.',400,'invalid_adjustment');if(!store.getUser(value.userId)||!value.reason)throw fail('User and reason are required.',400,'invalid_adjustment');const id=randomUUID();if(Math.abs(amount)>=config.highRiskAdjustmentThreshold){store.adjustments.set(id,{id,userId:value.userId,amount,reason:value.reason,status:'pending_approval',requestedBy:admin.actor,createdAt:clock()});store.audit.write({actor:admin.actor,action:'coins.adjustment_requested',targetType:'adjustment',targetId:id,metadata:{userId:value.userId,amount}});return reply(202,{adjustment:store.adjustments.get(id)});}const entry=store.appendLedger({userId:value.userId,amount,reason:'manual_adjustment',idempotencyKey:`adjustment:${id}`,referenceType:'adjustment',referenceId:id});store.audit.write({actor:admin.actor,action:'coins.adjustment_applied',targetType:'adjustment',targetId:id,metadata:{amount,reason:value.reason}});return reply(201,{entry});}
        const approve=path.match(/^\/v1\/admin\/coins\/adjustments\/([a-f0-9-]+)\/approve$/);if(method==='POST'&&approve){const admin=requireAdmin(req,['admin','finance']);const adjustment=store.adjustments.get(approve[1]);if(!adjustment||adjustment.status!=='pending_approval')throw fail('Adjustment not found.',404,'adjustment_not_found');if(adjustment.requestedBy===admin.actor)throw fail('A different administrator must approve this adjustment.',409,'dual_approval_required');adjustment.status='approved';adjustment.approvedBy=admin.actor;adjustment.approvedAt=clock();const entry=store.appendLedger({userId:adjustment.userId,amount:adjustment.amount,reason:'manual_adjustment',idempotencyKey:`adjustment:${adjustment.id}`,referenceType:'adjustment',referenceId:adjustment.id});store.audit.write({actor:admin.actor,action:'coins.adjustment_approved',targetType:'adjustment',targetId:adjustment.id,metadata:{amount:adjustment.amount}});return reply(200,{entry});}
        throw fail('Administrative route not found.',404,'not_found');
      }
      return reply(404,{error:{code:'not_found',message:'Route not found.',requestId}});
    }catch(error){store.metrics.increment('http_requests_total',{status:String(error.status??500),route:req.url?.split('?')[0]||'unknown'});console.error(JSON.stringify({level:'error',requestId,message:error.message,code:error.code??'internal_error'}));return problem(res,error,requestId);}finally{store.metrics.observe('http_request_duration_ms',clock()-started,{method:req.method||'GET'});}
  };
}
