function number(name,fallback,{min=1}={}){const value=Number(process.env[name]??fallback);if(!Number.isFinite(value)||value<min)throw new Error(`Invalid ${name}`);return value;}
function bool(name,fallback=false){return String(process.env[name]??fallback).toLowerCase()==='true';}
function list(name,fallback=''){return String(process.env[name]??fallback).split(',').map(item=>item.trim()).filter(Boolean);}
function json(name,fallback){const raw=process.env[name];if(raw===undefined||raw==='')return structuredClone(fallback);try{return JSON.parse(raw);}catch{throw new Error(`Invalid ${name}`);}}
function topupOffers(value){if(!Array.isArray(value))throw new Error('Invalid TOPUP_OFFERS_JSON');return value.map(item=>{const id=String(item.id||'').trim();const label=String(item.label||'').trim();const coins=Number(item.coins);const amountPkr=Number(item.amountPkr);if(!/^[a-z0-9-]+$/.test(id)||!label||!Number.isInteger(coins)||coins<1||!Number.isFinite(amountPkr)||amountPkr<1)throw new Error('Invalid TOPUP_OFFERS_JSON');return{id,label,coins,amountPkr,status:item.status==='disabled'?'disabled':'live',recommended:Boolean(item.recommended)};});}
function voucherCodes(value){if(!value||Array.isArray(value)||typeof value!=='object')throw new Error('Invalid VOUCHER_CODES_JSON');const result={};for(const [code,reward] of Object.entries(value)){const normalized=String(code).trim().toUpperCase();const coins=Number(reward);if(!/^[A-Z0-9-]{4,32}$/.test(normalized)||!Number.isInteger(coins)||coins<1)throw new Error('Invalid VOUCHER_CODES_JSON');result[normalized]=coins;}return result;}
const ADMIN_ROLES=new Set(['admin','operator','support','security','finance']);
function adminPrincipals(value,legacy,nodeEnv){if(value===undefined)value=[];if(!Array.isArray(value))throw new Error('Invalid ADMIN_PRINCIPALS_JSON');const result=value.map(item=>{const id=String(item.id||'').trim();const key=String(item.key||'');const roles=[...new Set((item.roles||[]).map(role=>String(role).trim().toLowerCase()))];if(!/^[a-z0-9][a-z0-9_.-]{2,63}$/i.test(id)||key.length<16||!roles.length||roles.some(role=>!ADMIN_ROLES.has(role)))throw new Error('Invalid ADMIN_PRINCIPALS_JSON');return{id,key,roles};});if(nodeEnv!=='production')legacy.forEach((key,index)=>result.push({id:`local-${index+1}`,key,roles:[...ADMIN_ROLES]}));return result;}
function adminIdentityRoles(value){if(!value||Array.isArray(value)||typeof value!=='object')throw new Error('Invalid ADMIN_IDENTITY_ROLES_JSON');const result={};for(const [identity,roles] of Object.entries(value)){if(!/^[a-z0-9][a-z0-9_.:@+-]{2,127}$/i.test(identity)||!Array.isArray(roles))throw new Error('Invalid ADMIN_IDENTITY_ROLES_JSON');const normalized=[...new Set(roles.map(role=>String(role).trim().toLowerCase()))];if(!normalized.length||normalized.some(role=>!ADMIN_ROLES.has(role)))throw new Error('Invalid ADMIN_IDENTITY_ROLES_JSON');result[identity]=normalized;}return result;}
export function loadConfig(overrides={}){const nodeEnv=overrides.nodeEnv??process.env.NODE_ENV??'development';const legacyAdminKeys=overrides.adminApiKeys??list('ADMIN_API_KEYS');const adminAuthMode=overrides.adminAuthMode??process.env.ADMIN_AUTH_MODE??(nodeEnv==='production'?'signed-headers':'local-key');if(nodeEnv==='production'&&adminAuthMode!=='signed-headers')throw new Error('Production requires ADMIN_AUTH_MODE=signed-headers.');return Object.freeze({
  nodeEnv,port:overrides.port??number('PORT',8081),publicOrigin:overrides.publicOrigin??process.env.PUBLIC_ORIGIN??'http://localhost:8080',allowedOrigins:overrides.allowedOrigins??list('ALLOWED_ORIGINS',process.env.PUBLIC_ORIGIN??'http://localhost:8080'),
  databaseUrl:overrides.databaseUrl??process.env.DATABASE_URL??'',databaseSsl:overrides.databaseSsl??bool('DATABASE_SSL',nodeEnv==='production'),databaseCa:overrides.databaseCa??process.env.DATABASE_CA_PEM??'',requireDatabase:overrides.requireDatabase??bool('REQUIRE_DATABASE',nodeEnv==='production'),
  sessionCookieName:overrides.sessionCookieName??process.env.SESSION_COOKIE_NAME??'ga_session',csrfCookieName:overrides.csrfCookieName??process.env.CSRF_COOKIE_NAME??'ga_csrf',sessionTtlSeconds:overrides.sessionTtlSeconds??number('SESSION_TTL_SECONDS',2592000),sessionRotationSeconds:overrides.sessionRotationSeconds??number('SESSION_ROTATION_SECONDS',86400),
  otpTtlSeconds:overrides.otpTtlSeconds??number('OTP_TTL_SECONDS',300),otpResendSeconds:overrides.otpResendSeconds??number('OTP_RESEND_SECONDS',30),otpMaxAttempts:overrides.otpMaxAttempts??number('OTP_MAX_ATTEMPTS',5),otpAccountLimit:overrides.otpAccountLimit??number('OTP_ACCOUNT_LIMIT',5),otpIpLimit:overrides.otpIpLimit??number('OTP_IP_LIMIT',20),otpDeviceLimit:overrides.otpDeviceLimit??number('OTP_DEVICE_LIMIT',10),allowDebugOtp:overrides.allowDebugOtp??bool('ALLOW_DEBUG_OTP',nodeEnv!=='production'),
  otpProviderMode:overrides.otpProviderMode??process.env.OTP_PROVIDER_MODE??(nodeEnv==='production'?'disabled':'mock'),otpPrimaryName:overrides.otpPrimaryName??process.env.OTP_PRIMARY_NAME??'primary',otpPrimaryEndpoint:overrides.otpPrimaryEndpoint??process.env.OTP_PRIMARY_ENDPOINT??'',otpPrimaryApiKey:overrides.otpPrimaryApiKey??process.env.OTP_PRIMARY_API_KEY??'',otpSecondaryName:overrides.otpSecondaryName??process.env.OTP_SECONDARY_NAME??'secondary',otpSecondaryEndpoint:overrides.otpSecondaryEndpoint??process.env.OTP_SECONDARY_ENDPOINT??'',otpSecondaryApiKey:overrides.otpSecondaryApiKey??process.env.OTP_SECONDARY_API_KEY??'',
  brevoApiKey:overrides.brevoApiKey??process.env.BREVO_API_KEY??'',brevoSenderEmail:overrides.brevoSenderEmail??process.env.BREVO_SENDER_EMAIL??process.env.BREVO_FROM_EMAIL??'',brevoSenderName:overrides.brevoSenderName??process.env.BREVO_SENDER_NAME??process.env.BREVO_FROM_NAME??'Game Arena',brevoSmsSender:overrides.brevoSmsSender??process.env.BREVO_SMS_SENDER??'',
  jazzcashMode:overrides.jazzcashMode??process.env.JAZZCASH_MODE??'disabled',jazzcashWebhookSecret:overrides.jazzcashWebhookSecret??process.env.JAZZCASH_WEBHOOK_SECRET??'',jazzcashMerchantId:overrides.jazzcashMerchantId??process.env.JAZZCASH_MERCHANT_ID??'',jazzcashPassword:overrides.jazzcashPassword??process.env.JAZZCASH_PASSWORD??'',jazzcashIntegritySalt:overrides.jazzcashIntegritySalt??process.env.JAZZCASH_INTEGRITY_SALT??'',jazzcashActionUrl:overrides.jazzcashActionUrl??process.env.JAZZCASH_ACTION_URL??'',jazzcashReturnUrl:overrides.jazzcashReturnUrl??process.env.JAZZCASH_RETURN_URL??'',
  adminAuthMode,adminPrincipals:overrides.adminPrincipals??adminPrincipals(overrides.adminPrincipalsJson??json('ADMIN_PRINCIPALS_JSON',[]),legacyAdminKeys,nodeEnv),adminProxySecret:overrides.adminProxySecret??process.env.ADMIN_PROXY_SECRET??'',adminProxyMaxSkewSeconds:overrides.adminProxyMaxSkewSeconds??number('ADMIN_PROXY_MAX_SKEW_SECONDS',60),adminIdentityRoles:overrides.adminIdentityRoles??adminIdentityRoles(overrides.adminIdentityRolesJson??json('ADMIN_IDENTITY_ROLES_JSON',{})),
  rewardDailyCap:overrides.rewardDailyCap??number('REWARD_DAILY_CAP',1000),highRiskAdjustmentThreshold:overrides.highRiskAdjustmentThreshold??number('HIGH_RISK_ADJUSTMENT_THRESHOLD',5000),retentionDays:overrides.retentionDays??number('ACCOUNT_RETENTION_DAYS',30),legalHoldUserIds:overrides.legalHoldUserIds??list('LEGAL_HOLD_USER_IDS'),competitionsEnabled:overrides.competitionsEnabled??bool('COMPETITIONS_ENABLED',nodeEnv!=='production'),allowExternalGames:overrides.allowExternalGames??bool('ALLOW_EXTERNAL_GAMES',nodeEnv!=='production'),
  supportMode:overrides.supportMode??process.env.SUPPORT_DELIVERY_MODE??'disabled',supportEndpoint:overrides.supportEndpoint??process.env.SUPPORT_DELIVERY_ENDPOINT??'',supportSecret:overrides.supportSecret??process.env.SUPPORT_DELIVERY_SECRET??'',supportRateLimit:overrides.supportRateLimit??number('SUPPORT_RATE_LIMIT',5),
  freePlayDailyLimit:overrides.freePlayDailyLimit??number('FREE_PLAY_DAILY_LIMIT',0,{min:0}),multiplayerRoomTtlSeconds:overrides.multiplayerRoomTtlSeconds??number('MULTIPLAYER_ROOM_TTL_SECONDS',3600),
  topupOffers:overrides.topupOffers??topupOffers(json('TOPUP_OFFERS_JSON',[])),voucherCodes:overrides.voucherCodes??voucherCodes(json('VOUCHER_CODES_JSON',{}))
});}