import {randomUUID} from 'node:crypto';
import {readJson,send,problem,corsHeaders} from './lib/http.mjs';
import {assertCsrf,parseCookies,requestIp,sha256} from './lib/security.mjs';
const fail=(message,status=400,code='invalid_request',details)=>Object.assign(new Error(message),{status,code,details});
const publicRoom=room=>({id:room.id,joinCode:room.joinCode,gameId:room.gameId,name:room.name,maxPlayers:room.maxPlayers,players:room.players,status:room.status,hostName:room.hostName,createdAt:room.createdAt,expiresAt:room.expiresAt});
export function createMvpApp({config,store,payments,clock=()=>Date.now()}){
  function authContext(req){const cookies=parseCookies(req.headers.cookie);const token=cookies[config.sessionCookieName];if(!token)return null;const session=store.getSession(sha256(token));if(!session)return null;const user=store.getUser(session.userId);return user?{user,session}:null;}
  function requireUser(req){const context=authContext(req);if(!context)throw fail('Sign in is required.',401,'authentication_required');return context;}
  function mutation(req){assertCsrf(req,config);const origin=req.headers.origin;if(origin&&config.allowedOrigins.length&&!config.allowedOrigins.includes(origin))throw fail('Origin is not allowed.',403,'origin_rejected');}
  return async function mvp(req,res){const url=new URL(req.url,'http://localhost');const path=url.pathname;const method=req.method??'GET';const origin=req.headers.origin;const cors=corsHeaders(origin,config.allowedOrigins);const reply=(status,payload,headers={})=>send(res,status,payload,{...cors,...headers});const requestId=String(req.headers['x-request-id']||randomUUID()).slice(0,80);try{
    if(method==='OPTIONS'&&origin&&config.allowedOrigins.includes(origin)&&path.startsWith('/v1/'))return reply(204,null,{'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,x-csrf-token,x-request-id,idempotency-key,x-device-id','access-control-max-age':'600'});
    if(method==='POST'&&path==='/v1/play-sessions'&&config.freePlayDailyLimit>0){const {user}=requireUser(req);mutation(req);const entitlement=store.getEntitlement(user.id,clock());if(entitlement.tier!=='premium'){const since=clock()-clock()%86400000;const starts=[...store.playSessions.values()].filter(item=>item.userId===user.id&&item.startedAt>=since).length;if(starts>=config.freePlayDailyLimit)throw fail('Daily free-play limit reached. Upgrade to Game Arena+ or try again tomorrow.',429,'free_play_limit_reached',{limit:config.freePlayDailyLimit});}return false;}
    const paymentMatch=path.match(/^\/v1\/payments\/([a-f0-9-]+)$/);if(method==='GET'&&paymentMatch){const {user}=requireUser(req);const transaction=store.getTransaction(paymentMatch[1]);if(!transaction||transaction.userId!==user.id)throw fail('Transaction not found.',404,'transaction_not_found');const entitlement=store.getEntitlement(user.id,clock());return reply(200,{transactionId:transaction.id,status:transaction.status,kind:transaction.kind||'membership',planId:transaction.planId,offerId:transaction.offerId,coins:transaction.coins,amountPkr:transaction.amountPkr,balance:store.wallet(user.id),entitlement});}
    if(method==='GET'&&path==='/v1/offers/topups'){const context=authContext(req);const premium=context?store.getEntitlement(context.user.id,clock()).tier==='premium':false;const offers=config.topupOffers.filter(item=>item.status==='live').map(item=>({...item,memberAmountPkr:premium?Math.max(1,Math.round(item.amountPkr*.9)):item.amountPkr,memberDiscountPercent:premium?10:0}));return reply(200,{enabled:offers.length>0,offers});}
    if(method==='POST'&&path==='/v1/offers/topups/checkout'){const {user}=requireUser(req);mutation(req);const {value}=await readJson(req);const offer=config.topupOffers.find(item=>item.id===value.offerId&&item.status==='live');if(!offer)throw fail('Top-up offer is not available.',404,'offer_not_found');const premium=store.getEntitlement(user.id,clock()).tier==='premium';const transaction=await payments.checkoutTopup({userId:user.id,offer,idempotencyKey:req.headers['idempotency-key'],isPremium:premium});return reply(201,{transactionId:transaction.id,status:transaction.status,provider:'JazzCash',kind:'topup',offerId:transaction.offerId,coins:transaction.coins,amountPkr:transaction.amountPkr,checkout:transaction.checkout,redirectUrl:transaction.checkout?.redirectUrl});}
    if(method==='POST'&&path==='/v1/vouchers/redeem'){const {user}=requireUser(req);mutation(req);const {value}=await readJson(req);const code=String(value.code||'').trim().toUpperCase();const reward=config.voucherCodes[code];if(!reward)throw fail('Voucher is invalid or expired.',404,'voucher_not_found');const result=store.redeemVoucher({userId:user.id,code,reward});return reply(result.duplicate?200:201,{reward:result.reward,balance:result.balance,duplicate:Boolean(result.duplicate)});}
    if(method==='GET'&&path==='/v1/multiplayer/rooms')return reply(200,{rooms:store.listMultiplayerRooms(clock()).map(publicRoom)},{'cache-control':'public, max-age=5'});
    if(method==='POST'&&path==='/v1/multiplayer/rooms'){const {user}=requireUser(req);mutation(req);const {value}=await readJson(req);const game=store.getGame(value.gameId);if(!game)throw fail('Game not found.',404,'game_not_found');if(!game.multiplayer)throw fail('This game does not support multiplayer rooms.',409,'multiplayer_unavailable');const name=String(value.name||'').trim();const maxPlayers=Number(value.maxPlayers);if(name.length<3||name.length>50)throw fail('Room name must be between 3 and 50 characters.',400,'invalid_room_name');if(![2,4].includes(maxPlayers))throw fail('Room size must be 2 or 4 players.',400,'invalid_room_size');const room=store.createMultiplayerRoom({userId:user.id,hostName:user.displayName||'Player',gameId:game.id,name,maxPlayers,ttlSeconds:config.multiplayerRoomTtlSeconds,now:clock()});return reply(201,{room:publicRoom(room)});}
    const roomJoin=path.match(/^\/v1\/multiplayer\/rooms\/([a-f0-9-]+)\/join$/);if(method==='POST'&&roomJoin){const {user}=requireUser(req);mutation(req);const room=store.joinMultiplayerRoom({roomId:roomJoin[1],userId:user.id,now:clock()});return reply(200,{room:publicRoom(room)});}
    if(method==='POST'&&path==='/v1/support/tickets'){const context=authContext(req);const ipHash=sha256(requestIp(req));if(store.hitRateLimit(`support:${context?.user.id||ipHash}`,config.supportRateLimit,3600000,clock()))throw fail('Too many support requests. Try again later.',429,'rate_limited');const {value}=await readJson(req,65536);const topic=String(value.topic||'Other').trim().slice(0,80);const message=String(value.message||'').trim();const reference=String(value.reference||'').trim().slice(0,100);if(message.length<10||message.length>1500)throw fail('Support message must be between 10 and 1500 characters.',400,'invalid_support_message');const ticket=store.createSupportTicket({userId:context?.user.id||null,topic,message,reference});return reply(201,{ticket:{id:ticket.id,status:ticket.status,createdAt:ticket.createdAt}});}
    return false;
  }catch(error){if(error.status===undefined&&String(error.message).includes('Room'))error.status=409;problem(res,error,requestId);return true;}}
}
