import {createServer} from 'node:http';
import {loadConfig} from './config.mjs';
import {createApp} from './app.mjs';
import {createMvpApp} from './mvp-app.mjs';
import {createSupplementalApp} from './admin-app.mjs';
import {MemoryStore} from './adapters/memory-store.mjs';
import {assertNormalizedPostgresRuntime} from './lib/persistence-readiness.mjs';
import {JazzCashAdapter} from './adapters/jazzcash.mjs';
import {SupportDelivery} from './adapters/support-delivery.mjs';
import {DisabledOtpProvider,HttpOtpProvider,MockOtpProvider,OtpDeliveryRouter} from './adapters/otp-delivery.mjs';
import {PaymentService} from './services/payments.mjs';
import {RewardPolicy} from './services/reward-policy.mjs';
import {processAccountRetention} from './services/account-retention.mjs';
const config=loadConfig();let store;if(config.databaseUrl){const {PostgresStore}=await import('./adapters/postgres-store.mjs');store=await PostgresStore.connect({connectionString:config.databaseUrl,ssl:config.databaseSsl,ca:config.databaseCa});assertNormalizedPostgresRuntime(store,{required:config.nodeEnv==='production'});}else{if(config.requireDatabase)throw new Error('DATABASE_URL is required in production.');store=new MemoryStore();}
if(!config.allowExternalGames){for(const game of store.games)if(game.version==='external'||!game.version){game.status='paused';game.rolloutPercentage=0;}}
const providers=config.otpProviderMode==='mock'?[new MockOtpProvider()]:config.otpProviderMode==='http'?[new HttpOtpProvider({name:config.otpPrimaryName,endpoint:config.otpPrimaryEndpoint,apiKey:config.otpPrimaryApiKey}),new HttpOtpProvider({name:config.otpSecondaryName,endpoint:config.otpSecondaryEndpoint,apiKey:config.otpSecondaryApiKey})]:[new DisabledOtpProvider()];
const otpDelivery=new OtpDeliveryRouter({providers,audit:store.audit,metrics:store.metrics});const jazzcash=new JazzCashAdapter(config);const payments=new PaymentService({store,provider:jazzcash});const rewardPolicy=new RewardPolicy({config,store});const supportDelivery=new SupportDelivery({mode:config.supportMode,endpoint:config.supportEndpoint,secret:config.supportSecret});const primary=createApp({config,store,jazzcash,otpDelivery,payments,rewardPolicy});const mvp=createMvpApp({config,store,payments,supportDelivery});const supplemental=createSupplementalApp({config,store});
function durableResponse(res){if(!store.commit)return;const originalWriteHead=res.writeHead.bind(res);const originalEnd=res.end.bind(res);const chunks=[];let ending=false;res.writeHead=(statusCode,statusMessage,headers)=>{res.statusCode=statusCode;if(typeof statusMessage==='object'&&statusMessage)headers=statusMessage;if(headers)for(const [name,value]of Object.entries(headers))res.setHeader(name,value);return res;};res.write=(chunk,encoding,callback)=>{if(chunk!==undefined&&chunk!==null)chunks.push(Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk,typeof encoding==='string'?encoding:undefined));if(typeof encoding==='function')encoding();else callback?.();return true;};res.end=(chunk,encoding,callback)=>{if(ending)return res;ending=true;if(chunk!==undefined&&chunk!==null)chunks.push(Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk,typeof encoding==='string'?encoding:undefined));const done=typeof encoding==='function'?encoding:callback;store.commit().then(()=>{originalWriteHead(res.statusCode);originalEnd(chunks.length?Buffer.concat(chunks):undefined,done);}).catch(error=>{console.error(JSON.stringify({level:'error',message:'PostgreSQL commit before response failed',error:error.message}));for(const name of res.getHeaderNames())res.removeHeader(name);originalWriteHead(503,{'content-type':'application/json','cache-control':'no-store'});originalEnd(JSON.stringify({error:{code:'persistence_unavailable',message:'The request could not be committed. Please retry.'}}),done);});return res;};}
const server=createServer(async(req,res)=>{durableResponse(res);try{if(await supplemental(req,res)!==false)return;if(await mvp(req,res)!==false)return;await primary(req,res);}catch(error){console.error(JSON.stringify({level:'error',message:'Unhandled request error',error:error.message}));if(!res.headersSent){res.writeHead(500,{'content-type':'application/json'});res.end(JSON.stringify({error:{code:'internal_error',message:'Unexpected server error.'}}));}}});
const retention=async()=>{try{const result=processAccountRetention(store,{retentionDays:config.retentionDays,legalHoldUserIds:config.legalHoldUserIds});if(result.processed)await store.commit?.();}catch(error){console.error(JSON.stringify({level:'error',message:'Account retention processing failed',error:error.message}));}};const retentionTimer=setInterval(retention,3600000);retentionTimer.unref();await retention();
server.requestTimeout=15000;server.headersTimeout=16000;server.keepAliveTimeout=5000;server.maxRequestsPerSocket=1000;server.listen(config.port,'0.0.0.0',()=>console.log(JSON.stringify({level:'info',message:'Game Arena API listening',port:config.port,mode:config.nodeEnv,database:config.databaseUrl?'postgres':'memory',payments:config.jazzcashMode,otp:config.otpProviderMode,support:config.supportMode,externalGames:config.allowExternalGames})));
for(const signal of ['SIGINT','SIGTERM'])process.on(signal,()=>{clearInterval(retentionTimer);server.close(async()=>{await store.close?.();process.exit(0);});});
