import {games,genres,premiumFeatures} from '../data.js';
import {escapeHtml,money} from '../ui.js';
import {openGame} from '../game-player.js';
import {track} from '../analytics.js';

const featured=games.slice(0,6);
function gameCard(game){return `<article class="spotlight-card" style="--art:${game.art}"><div class="spotlight-copy"><span class="badge ${game.tier==='premium'?'premium':''}">${game.tier==='premium'?'Arena+':'Free'}</span>${game.multiplayer?'<span class="badge">Multiplayer</span>':''}<h3>${escapeHtml(game.title)}</h3><p>${escapeHtml(game.description)}</p><button class="button primary" data-home-play="${game.id}" type="button">Play now</button></div></article>`;}
export function renderHome(){return `<section class="home-page"><section class="landing-hero"><div class="hero-copy"><span class="eyebrow">Pakistan's mobile game arena</span><h1>Play instantly.<br>Compete. Earn.</h1><p>Discover casual and multiplayer games, join tournaments, earn Arena Coins and unlock the full catalogue with Game Arena+.</p><div class="hero-actions"><a class="button primary" href="#/feed">Start playing</a><a class="button gold" href="#/premium">Explore Arena+</a></div><div class="hero-proof"><span><b>1M+</b><small>source-platform downloads</small></span><span><b>61</b><small>submitted games reviewed</small></span><span><b>11</b><small>genre groups</small></span></div></div><div class="hero-device" aria-hidden="true"><div class="device-card"><span class="badge">Instant play</span><strong>Arena Dash</strong><small>One tap. No install.</small><div class="device-button">▶</div></div></div></section>
<section class="section-block"><header class="section-head"><div><span class="eyebrow">Featured now</span><h2>Find your next game</h2></div><a href="#/library">View all games →</a></header><div class="spotlight-grid">${featured.map(gameCard).join('')}</div></section>
<section class="section-block feature-band"><header class="section-head"><div><span class="eyebrow">Everything in one arena</span><h2>Built for playing, not waiting</h2></div></header><div class="feature-grid"><article><span>⚡</span><h3>Instant play</h3><p>Launch HTML5 games directly in the browser.</p></article><article><span>⌕</span><h3>Genre discovery</h3><p>Browse ${genres.length-1} active genre groups and save favourites.</p></article><article><span>♟</span><h3>Multiplayer</h3><p>Create or join game rooms from the competition hub.</p></article><article><span>🏆</span><h3>Tournaments</h3><p>Join open events and follow verified leaderboard scores.</p></article><article><span>◉</span><h3>Rewards</h3><p>Earn Arena Coins from verified play and challenges.</p></article><article><span>🎟</span><h3>Vouchers & top-ups</h3><p>Redeem offers and access member discounts when enabled.</p></article></div></section>
<section class="section-block premium-banner"><div><span class="eyebrow">Game Arena+</span><h2>Unlock the full Game Arena catalogue.</h2><p>${premiumFeatures.slice(0,4).join(' · ')}</p></div><div class="premium-price"><strong>${money(299)}</strong><small>fixed-duration month</small><a class="button gold" href="#/premium">See plans</a></div></section>
<section class="section-block steps"><header class="section-head"><div><span class="eyebrow">Simple activation</span><h2>Four steps to premium</h2></div></header><div class="step-grid"><article><b>1</b><h3>Select plan</h3><p>Choose monthly or yearly access.</p></article><article><b>2</b><h3>Pay via JazzCash</h3><p>Continue to the provider's secure checkout.</p></article><article><b>3</b><h3>Premium activates</h3><p>The server confirms payment and entitlement.</p></article><article><b>4</b><h3>Benefits unlock</h3><p>Premium games, tournaments and stronger rewards become available.</p></article></div></section></section>`;}
export function bindHome(){document.querySelectorAll('[data-home-play]').forEach(button=>button.addEventListener('click',()=>{const game=games.find(item=>item.id===button.dataset.homePlay);track('game_play_intent',{source:'home',gameId:game?.id});openGame(game);}));}
