import {games,genres} from '../data.js';
import {getState,toggleFavourite,isPremium} from '../state.js';
import {escapeHtml,toast} from '../ui.js';
import {openGame} from '../game-player.js';
let query='';let genre='All';let tab='all';
function filtered(){const state=getState();let list=games.filter(game=>(genre==='All'||game.genre===genre)&&(`${game.title} ${game.description} ${game.genre}`.toLowerCase().includes(query.toLowerCase())));if(tab==='saved')list=list.filter(game=>state.favourites.includes(game.id));if(tab==='recent')list=state.recent.map(id=>list.find(game=>game.id===id)).filter(Boolean);if(tab==='downloads')list=list.filter(game=>game.downloadUrl&&game.tier==='free');return list;}
function card(game){const locked=game.tier==='premium'&&!isPremium();const saved=getState().favourites.includes(game.id);const offlineEligible=game.tier==='free'&&Boolean(game.downloadUrl);return `<article class="card game-card" style="--art:${game.art}"><div class="game-card-shade"></div><div class="game-card-content"><div class="badge-row"><span class="badge ${game.tier==='premium'?'premium':''}">${game.tier==='premium'?'Arena+':'Free'}</span>${game.multiplayer?'<span class="badge">Multiplayer</span>':''}</div><h2>${escapeHtml(game.title)}</h2><p>${escapeHtml(game.description)}</p><div class="game-actions"><button class="button ${locked?'gold':'primary'}" data-play="${game.id}" type="button">${locked?'Unlock':'Play'}</button><button class="button secondary" data-save="${game.id}" aria-pressed="${saved}" type="button">${saved?'★':'☆'}</button>${offlineEligible?`<button class="button secondary" data-download="${game.id}" type="button" aria-label="Save ${escapeHtml(game.title)} for offline access">↓</button>`:''}</div></div></article>`;}
export function renderLibrary(){const list=filtered();return `<section class="page"><header class="page-head"><div><span class="eyebrow">Games catalogue</span><h1>Discover your next game</h1><p>Search, save, revisit and launch games from one mobile-first library.</p></div><a class="button secondary" href="#/feed">Open swipe feed</a></header><div class="tab-row" role="tablist"><button class="chip ${tab==='all'?'active':''}" data-tab="all">All</button><button class="chip ${tab==='saved'?'active':''}" data-tab="saved">Saved</button><button class="chip ${tab==='recent'?'active':''}" data-tab="recent">Recent</button><button class="chip ${tab==='downloads'?'active':''}" data-tab="downloads">Offline</button></div><div class="searchbar"><input id="game-search" type="search" value="${escapeHtml(query)}" placeholder="Search ${games.length} games" aria-label="Search games"></div><div class="chip-row" aria-label="Genres">${genres.map(item=>`<button class="chip ${item===genre?'active':''}" data-genre="${item}" type="button">${escapeHtml(item)}</button>`).join('')}</div><div id="library-grid" class="grid">${list.map(card).join('')}</div><div id="library-empty" class="empty" ${list.length?'hidden':''}><h3>No games here yet</h3><p>Try another filter or play a game to build your recent list.</p></div></section>`;}
export function bindLibrary(){const root=document.querySelector('#app');const repaint=()=>{root.innerHTML=renderLibrary();bindLibrary();};document.querySelector('#game-search').addEventListener('input',event=>{query=event.target.value;repaint();});root.querySelectorAll('[data-genre]').forEach(button=>button.addEventListener('click',()=>{genre=button.dataset.genre;repaint();}));root.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',()=>{tab=button.dataset.tab;repaint();}));root.querySelectorAll('[data-save]').forEach(button=>button.addEventListener('click',()=>{toggleFavourite(button.dataset.save);repaint();}));root.querySelectorAll('[data-play]').forEach(button=>button.addEventListener('click',()=>openGame(games.find(item=>item.id===button.dataset.play))));root.querySelectorAll('[data-download]').forEach(button=>button.addEventListener('click',async()=>{const game=games.find(item=>item.id===button.dataset.download);if(!game?.downloadUrl||game.tier!=='free'){toast('Offline access is currently available only for free games.');return;}try{const cache=await caches.open('game-arena-downloads-v1');await cache.add(game.downloadUrl);toast(`${game.title} saved for supported offline access.`);}catch{toast('This game could not be saved offline.');}}));}
