import {games,genres} from '../data.js';
import {getState,toggleFavourite,isPremium} from '../state.js';
import {escapeHtml,requireAuth,toast} from '../ui.js';
import {track} from '../analytics.js';

let query='';let genre='All';
function filtered(){return games.filter(game=>(genre==='All'||game.genre===genre)&&(`${game.title} ${game.description} ${game.genre}`.toLowerCase().includes(query.toLowerCase())));}
function card(game){const locked=game.tier==='premium'&&!isPremium();const saved=getState().favourites.includes(game.id);return `<article class="card game-card" style="--art:${game.art}"><div><span class="badge ${game.tier==='premium'?'premium':''}">${game.tier==='premium'?'Arena+':'Free'}</span><h2>${escapeHtml(game.title)}</h2><p>${escapeHtml(game.description)}</p><div class="game-actions"><button class="button ${locked?'gold':'primary'}" data-play="${game.id}" type="button">${locked?'Unlock':'Play'}</button><button class="button secondary" data-save="${game.id}" aria-pressed="${saved}" type="button">${saved?'★':'☆'}</button></div></div></article>`;}
export function renderLibrary(){return `<section class="page"><header class="page-head"><div><span class="eyebrow">Discover</span><h1>Find your next game</h1><p>Search a light, fast catalogue built for mobile.</p></div></header><div class="searchbar"><input id="game-search" type="search" value="${escapeHtml(query)}" placeholder="Search games" aria-label="Search games"></div><div class="chip-row" aria-label="Genres">${genres.map(item=>`<button class="chip ${item===genre?'active':''}" data-genre="${item}" type="button">${item}</button>`).join('')}</div><div id="library-grid" class="grid">${filtered().map(card).join('')}</div><div id="library-empty" class="empty" ${filtered().length?'hidden':''}>No games match this search.</div></section>`;}
export function bindLibrary(){const root=document.querySelector('#app');const repaint=()=>{document.querySelector('#library-grid').innerHTML=filtered().map(card).join('');document.querySelector('#library-empty').hidden=filtered().length>0;bindCards();};document.querySelector('#game-search').addEventListener('input',event=>{query=event.target.value;repaint();});root.querySelectorAll('[data-genre]').forEach(button=>button.addEventListener('click',()=>{genre=button.dataset.genre;renderInto();}));function renderInto(){root.innerHTML=renderLibrary();bindLibrary();}function bindCards(){root.querySelectorAll('[data-save]').forEach(button=>button.addEventListener('click',()=>{toggleFavourite(button.dataset.save);repaint();}));root.querySelectorAll('[data-play]').forEach(button=>button.addEventListener('click',async()=>{const game=games.find(item=>item.id===button.dataset.play);if(game.tier==='premium'&&!isPremium()){track('upgrade_view',{source:'library',gameId:game.id});location.hash='#/premium';return;}if(await requireAuth({type:'game',gameId:game.id}))toast('Game runtime ready for the game-build integration step');}));}bindCards();}
