import {plans as legacyPlans,premiumFeatures} from '../data.js';
import {getState,update,isPremium} from '../state.js';
import {money,membershipCheckout,escapeHtml,requireAuth,modal,closeModal,toast} from '../ui.js';
import {amountPkr,createBillingSubscription,fetchBillingPlans,linkBillingWallet,pollBillingStatus,submitWalletPortal} from '../billing-api.js';
import {track} from '../analytics.js';

let externalPlans=[];
let externalAvailable=false;
const normalizePlans=payload=>(Array.isArray(payload)?payload:(payload?.plans||[])).filter(item=>['monthly','yearly'].includes(String(item.code||item.planCode||item.id||''))).map(item=>({id:String(item.code||item.planCode||item.id),name:String(item.code||item.planCode||item.id)==='yearly'?'Yearly':'Monthly',price:amountPkr(item),period:String(item.interval||item.code||'month').replace('monthly','month').replace('yearly','year'),description:Number(item.trialHours??item.trial_hours??0)>0?`${Number(item.trialHours??item.trial_hours)}-hour trial, then automatic JazzCash billing.`:'Automatic JazzCash billing after wallet link.',recommended:Boolean(item.recommended),raw:item}));
function planCard(plan){const selected=getState().selectedPlan===plan.id;const recommended=Boolean(plan.recommended);return `<article class="card plan ${recommended?'recommended':''}">${recommended?'<span class="badge premium">Best value</span>':''}<h2>${escapeHtml(plan.name)}</h2><div class="price">${money(plan.price)} <small>/ ${escapeHtml(plan.period)}</small></div><p class="muted">${escapeHtml(plan.description)}</p><button class="button ${recommended?'gold':'primary'}" data-plan="${escapeHtml(plan.id)}" type="button" aria-pressed="${selected}">${isPremium()&&selected?'Current plan':`Choose ${escapeHtml(plan.name)}`}</button></article>`;}
function renderPlans(plans){const grid=document.querySelector('#premium-plan-grid');if(grid)grid.innerHTML=plans.map(planCard).join('');}
function renderExternalChrome(){const trust=document.querySelector('#premium-trust');if(trust)trust.innerHTML='<span>JazzCash wallet</span><span>Server-authoritative billing</span><span>Cancel or unlink anytime</span>';const faq=document.querySelector('#premium-faq');if(faq)faq.innerHTML='<article class="card card-body"><h3>How does billing work?</h3><p>Link your JazzCash wallet once. The payment service manages the trial and automatic plan billing until you cancel the subscription or unlink the wallet.</p></article><article class="card card-body"><h3>Where do I enter my MPIN?</h3><p>Only on JazzCash\'s hosted page. Game Arena never asks for or stores your MPIN.</p></article><article class="card card-body"><h3>What happens if I cancel?</h3><p>Future debits stop. Already-paid access remains available until the current paid period ends.</p></article>';}
function billingState(result){const sub=(result?.subscriptions||[])[0];return{sub,state:sub?.status||result?.status?.subscription_status||null,wallet:result?.wallet?.status||'none'};}
function hasOpenSubscription(result){return (result?.subscriptions||[]).some(item=>['initiated','trialing','active','past_due','paused'].includes(item.status));}
async function applyAuthoritativeStatus(result,planId){const {state,wallet}=billingState(result);if(result?.appEntitlement?.tier)update({entitlement:result.appEntitlement.tier,selectedPlan:planId||getState().selectedPlan});if(wallet==='failed'||['payment_failed','expired'].includes(state)){toast('JazzCash linking or payment was not completed. You can try again.');return false;}if(state==='trialing'){toast('JazzCash wallet linked. Game Arena+ trial is active.');return true;}if(state==='active'&&result?.status?.current_period_paid){toast('Game Arena+ payment confirmed and access is active.');return true;}if(state==='past_due'){toast('Payment is past due. JazzCash retry handling is automatic.');return Boolean(result?.appEntitlement?.tier==='premium');}if(state==='initiated'){toast('Wallet linked. First payment is being confirmed.');return false;}if(state==='canceled'){toast('Subscription is canceled. Paid-period access is retained where applicable.');return Boolean(result?.appEntitlement?.tier==='premium');}return false;}
async function reconcileOrResubscribe(plan){const current=await pollBillingStatus({attempts:4,intervalMs:1500});if(hasOpenSubscription(current)){await applyAuthoritativeStatus(current,plan.id);return current;}if(current?.wallet?.status!=='linked')return current;try{await createBillingSubscription({planCode:plan.id});}catch(error){if(!(error.status===409&&error.code==='already_subscribed'))throw error;}return pollBillingStatus({attempts:20,intervalMs:2500});}
async function resumeWalletLink(){const pending=JSON.parse(sessionStorage.getItem('game-arena:pending-wallet')||'null');if(!pending)return;try{const result=await pollBillingStatus({attempts:20,intervalMs:2500});const resolved=await applyAuthoritativeStatus(result,pending.planId);const {wallet,state}=billingState(result);if(wallet!=='pending'&&state!=='initiated')sessionStorage.removeItem('game-arena:pending-wallet');if(resolved){track('wallet_subscription_ready',{planId:pending.planId,state});location.hash='#/account';}}catch(error){toast(error.message);}}
async function walletCheckout(plan){if(!await requireAuth({type:'checkout',planId:plan.id}))return;track('wallet_link_start',{planId:plan.id});modal('Link JazzCash & activate Game Arena+',`<form id="wallet-link-form" class="stack"><div class="checkout-summary"><span><b>${escapeHtml(plan.name)}</b><small>${money(plan.price)} · automatic ${escapeHtml(plan.period)} billing</small></span><span class="jazzcash-mark">JC</span></div><p class="muted">Enter the JazzCash mobile number you want to link. Your MPIN is entered only on JazzCash's hosted page.</p><div class="field"><label for="billing-msisdn">JazzCash mobile number</label><input id="billing-msisdn" name="msisdn" inputmode="tel" autocomplete="tel" required pattern="\\+?[0-9]{11,15}" placeholder="03001234567"></div><label class="setting"><span><b>Automatic billing consent</b><small class="muted">I authorize recurring JazzCash debits for this plan until I cancel or unlink the wallet.</small></span><input name="consent" type="checkbox" required></label><button class="button gold" type="submit">Continue to JazzCash</button><p id="payment-status" role="status"></p></form>`);const form=document.querySelector('#wallet-link-form');form.addEventListener('submit',async event=>{event.preventDefault();const status=form.querySelector('#payment-status');const body=new FormData(form);status.textContent='Starting secure JazzCash wallet link…';try{let result;try{result=await linkBillingWallet({msisdn:body.get('msisdn'),planCode:plan.id});}catch(error){if(error.status===409&&error.code==='already_linked'){status.textContent='Wallet already linked. Checking Game Arena+ subscription…';const current=await reconcileOrResubscribe(plan);const ready=await applyAuthoritativeStatus(current,plan.id);closeModal();if(ready)location.hash='#/account';else toast('Subscription started. Payment confirmation is still pending.');return;}throw error;}sessionStorage.setItem('game-arena:pending-wallet',JSON.stringify({planId:plan.id,requestId:result.requestId||null,createdAt:Date.now()}));status.textContent='Redirecting to JazzCash…';if(!submitWalletPortal(result))throw new Error('JazzCash portal response was incomplete.');}catch(error){status.textContent=error.status===429?'Too many requests. Please retry shortly.':error.message;}});}

export function renderPremium(){return `<section class="page premium-page"><div class="premium-hero"><span class="eyebrow">Game Arena+</span><h1>More games. More ways to play.</h1><p>Unlock the full catalogue, premium challenges and tournaments, 2× Arena Coin rewards and a 10% member discount on supported top-ups.</p><div class="trust-row" id="premium-trust"><span>JazzCash checkout</span><span>Fixed-duration purchase</span><span>Server-confirmed activation</span></div></div>${isPremium()?'<div class="notice">Game Arena+ is active on this account.</div>':''}<div class="plan-grid" id="premium-plan-grid">${legacyPlans.map(planCard).join('')}</div><section class="card card-body premium-includes"><h2>Premium includes</h2><ul class="feature-list">${premiumFeatures.map(item=>`<li>${escapeHtml(item)}</li>`).join('')}</ul></section><section class="comparison card"><div class="compare-row compare-head"><span>Feature</span><b>Free</b><b>Arena+</b></div>${[['Catalogue','Selected','Full'],['Play limits','Configurable','No premium limits'],['Leaderboards','Basic','Premium challenges'],['Tournaments','Selected','Full access'],['Rewards','Standard','2× coins'],['Top-ups','Standard','10% discount']].map(row=>`<div class="compare-row"><strong>${row[0]}</strong><span>${row[1]}</span><span>${row[2]}</span></div>`).join('')}</section><section class="faq-grid" id="premium-faq"><article class="card card-body"><h3>Does it auto-renew?</h3><p>No. Monthly and yearly access are fixed-duration purchases until recurring billing is approved and implemented.</p></article><article class="card card-body"><h3>When does access activate?</h3><p>After JazzCash confirms payment to the backend and the entitlement becomes active.</p></article><article class="card card-body"><h3>What happens when it expires?</h3><p>Your account returns to the free tier. Progress and account data remain available.</p></article></section></section>`;}

export function bindPremium(){
  const grid=document.querySelector('#premium-plan-grid');if(!grid)return;
  externalPlans=[];externalAvailable=false;
  const readiness=(async()=>{try{const payload=await fetchBillingPlans();externalPlans=normalizePlans(payload);externalAvailable=Boolean(payload?.enabled!==false&&externalPlans.length);if(externalAvailable){renderPlans(externalPlans);renderExternalChrome();}}catch{externalAvailable=false;}return externalAvailable;})();
  grid.addEventListener('click',async event=>{const button=event.target.closest?.('[data-plan]');if(!button||!grid.contains(button))return;const selectedId=button.dataset.plan;await readiness;const source=externalAvailable?externalPlans:legacyPlans;const plan=source.find(item=>item.id===selectedId);if(!plan)return;update({selectedPlan:plan.id});track('plan_select',{planId:plan.id});if(isPremium())return;if(externalAvailable)await walletCheckout(plan);else await membershipCheckout(plan);});
  readiness.then(enabled=>{if(enabled&&sessionStorage.getItem('game-arena:pending-wallet'))resumeWalletLink();});
}
