import {challenges as fallbackChallenges,tournaments as fallbackTournaments,games} from '../data.js';
import {claimChallenge,fetchChallenges,fetchTournaments,joinTournament} from '../api.js';
import {getState,isPremium,update} from '../state.js';
import {escapeHtml,toast,requireAuth} from '../ui.js';
function targetText(item){if(typeof item.target==='string')return item.target;return item.target?.type==='completions'?`Complete ${item.target.value} runs`:`Score ${Number(item.target?.value||0).toLocaleString('en-PK')} points`;}
export function renderRewards(){const state=getState();const challenges=state.rewardsLoaded?state.liveChallenges:fallbackChallenges;const tournaments=state.rewardsLoaded?state.liveTournaments:fallbackTournaments;return `<section class="page"><header class="page-head"><div><span class="eyebrow">Arena Rewards</span><h1>${Number(state.coins).toLocaleString('en-PK')} coins</h1><p>Earn loyalty rewards through verified play, challenges and tournaments.</p></div></header><div class="notice">Arena Coins are non-transferable, non-withdrawable and have no cash value.</div><div class="metric-row" style="margin:1rem 0"><div class="metric"><b>${isPremium()?'2×':'1×'}</b><small>Reward rate</small></div><div class="metric"><b>${challenges.length}</b><small>Challenges</small></div><div class="metric"><b>${tournaments.length}</b><small>Events</small></div></div><section><h2>Challenges</h2><div class="reward-list">${challenges.map(item=>{const progress=item.progress?Math.min(100,Math.round(item.progress.value/item.progress.target*100)):Math.min(item.progress||0,100);return `<article class="card reward-item"><div><span class="badge ${item.premium?'premium':''}">${item.premium?'Arena+':'Open'}</span><h3>${escapeHtml(item.title)}</h3><p class="muted">${escapeHtml(targetText(item))} · ${item.reward} coins</p><div class="progress"><span style="width:${progress}%"></span></div></div><button class="button secondary" data-challenge="${item.id}" data-complete="${Boolean(item.progress?.complete)}" type="button">${item.progress?.complete?'Claim':'View'}</button></article>`;}).join('')}</div></section><section><h2>Tournaments</h2><div class="tournament-list">${tournaments.map(item=>{const game=games.find(game=>game.id===item.gameId);const starts=item.starts||new Intl.DateTimeFormat('en-PK',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Karachi'}).format(new Date(item.startsAt||Date.now()));return `<article class="card tournament-item"><div><span class="badge ${item.premium?'premium':''}">${item.premium?'Premium':'Open'}</span><h3>${escapeHtml(item.title)}</h3><p class="muted">${escapeHtml(game?.title||'Game')} · ${escapeHtml(starts)}</p></div><button class="button ${item.premium?'gold':'primary'}" data-tournament="${item.id}" data-premium="${item.premium}" type="button">Join</button></article>`;}).join('')}</div></section></section>`;}
export function bindRewards(){
  if(!getState().rewardsLoaded)Promise.all([fetchChallenges(),fetchTournaments()]).then(([challengeResult,tournamentResult])=>update({rewardsLoaded:true,liveChallenges:challengeResult.challenges,liveTournaments:tournamentResult.tournaments})).catch(()=>update({rewardsLoaded:true,liveChallenges:fallbackChallenges,liveTournaments:fallbackTournaments}));
  document.querySelectorAll('[data-challenge]').forEach(button=>button.addEventListener('click',async()=>{if(button.dataset.complete!=='true'){toast('Keep playing to complete this challenge.');return;}if(!await requireAuth({type:'challenge',id:button.dataset.challenge}))return;try{const result=await claimChallenge(button.dataset.challenge);update({coins:result.balance,rewardsLoaded:false});toast(`+${result.reward} Arena Coins`);}catch(error){toast(error.message);}}));
  document.querySelectorAll('[data-tournament]').forEach(button=>button.addEventListener('click',async()=>{if(button.dataset.premium==='true'&&!isPremium()){location.hash='#/premium';return;}if(!await requireAuth({type:'tournament',id:button.dataset.tournament}))return;try{await joinTournament(button.dataset.tournament);toast('Tournament entry confirmed.');button.disabled=true;button.textContent='Joined';}catch(error){toast(error.message);}}));
}
