import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {createSupplementalApp} from '../src/admin-app.mjs';
import {MemoryStore} from '../src/adapters/memory-store.mjs';
import {loadConfig} from '../src/config.mjs';
async function fixture(){const store=new MemoryStore();const config=loadConfig({nodeEnv:'test',port:1,publicOrigin:'http://localhost',allowedOrigins:['http://localhost'],adminApiKeys:['admin-key']});const supplemental=createSupplementalApp({config,store});const server=createServer(async(req,res)=>{if(await supplemental(req,res)===false){res.writeHead(404);res.end();}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));return{base:`http://127.0.0.1:${server.address().port}`,store,close:()=>new Promise(resolve=>server.close(resolve))};}
test('analytics accepts only allow-listed non-sensitive fields',async()=>{const f=await fixture();try{let response=await fetch(`${f.base}/v1/events`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:'web_vital',properties:{metric:'LCP',value:1200,email:'blocked@example.com'}})});assert.equal(response.status,202);assert.equal(f.store.metrics.counters.get('analytics_events_total:{"name":"web_vital"}'),1);response=await fetch(`${f.base}/v1/events`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:'unknown',properties:{}})});assert.equal(response.status,400);}finally{await f.close();}});
test('operations routes enforce roles and return live plus paused games',async()=>{const f=await fixture();try{assert.equal((await fetch(`${f.base}/v1/admin/games`)).status,401);let response=await fetch(`${f.base}/v1/admin/games`,{headers:{'x-admin-key':'admin-key','x-admin-role':'operator'}});assert.equal(response.status,200);const body=await response.json();assert.equal(body.games.length,47);assert.ok(body.games.some(item=>item.id==='arena-dash'&&item.status==='live'));for(const id of ['duck-hunter','ranger-vs-zombies','robotex','swat-vs-zombies']){const game=body.games.find(item=>item.id===id);assert.equal(game.status,'paused');assert.equal(game.rolloutPercentage,0);}response=await fetch(`${f.base}/v1/admin/reviews`,{headers:{'x-admin-key':'admin-key','x-admin-role':'support'}});assert.equal(response.status,200);assert.ok(Array.isArray((await response.json()).results));}finally{await f.close();}});
