import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {createApp} from '../src/app.mjs';
import {loadConfig} from '../src/config.mjs';
import {MemoryStore} from '../src/adapters/memory-store.mjs';
import {JazzCashAdapter} from '../src/adapters/jazzcash.mjs';
import {hmac} from '../src/lib/security.mjs';
import {catalogue,pilotCatalogue,quarantinedCatalogue} from '../src/catalogue/index.mjs';

async function fixture(){let now=Date.now();const clock=()=>now;const config=loadConfig({nodeEnv:'test',port:1,publicOrigin:'http://localhost',allowedOrigins:['http://localhost'],allowDebugOtp:true,jazzcashMode:'mock',jazzcashWebhookSecret:'test-secret',adminPrincipals:[{id:'security-admin',key:'security-key-123456789',roles:['security']},{id:'finance-admin',key:'finance-key-1234567890',roles:['finance']}],rewardDailyCap:1000,competitionsEnabled:true});const store=new MemoryStore();const jazzcash=new JazzCashAdapter(config);const server=createServer(createApp({config,store,jazzcash,clock}));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));return{base:`http://127.0.0.1:${server.address().port}`,store,advance(ms){now+=ms;},close:()=>new Promise(resolve=>server.close(resolve))};}
async function signIn(base,identifier='03001234567'){let response=await fetch(`${base}/v1/auth/otp`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identifier})});const challenge=await response.json();assert.equal(response.status,202);response=await fetch(`${base}/v1/auth/otp/verify`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({challengeId:challenge.challengeId,code:challenge.debugCode})});const body=await response.json();assert.equal(response.status,200);const setCookies=response.headers.getSetCookie?.()??[response.headers.get('set-cookie')];const values={};for(const line of setCookies.filter(Boolean))for(const part of line.split(/,(?=\s*[^;,]+=)/)){const pair=part.trim().split(';')[0];const index=pair.indexOf('=');values[pair.slice(0,index)]=pair.slice(index+1);}return{cookie:Object.entries(values).map(([key,value])=>`${key}=${value}`).join('; '),csrf:body.csrfToken,user:body.user};}
const headers=auth=>({'content-type':'application/json',cookie:auth.cookie,'x-csrf-token':auth.csrf,origin:'http://localhost'});
const paidPayload=transactionId=>({transactionId,status:'paid',providerReference:'JC-PAID',providerEventId:`event-${transactionId}`,merchantId:'mock-merchant',billReference:transactionId,amountMinor:29900,currency:'PKR'});

test('catalogue separates 42 active games, four controlled pilots and 17 source quarantines',()=>{assert.equal(catalogue.length,46);assert.equal(pilotCatalogue.length,4);assert.equal(quarantinedCatalogue.length,17);assert.equal(catalogue.filter(game=>game.status==='live').length,42);assert.ok(catalogue.filter(game=>game.status==='live').every(game=>game.gameUrl.startsWith('https://')));assert.ok(pilotCatalogue.every(game=>game.status==='paused'&&game.rolloutPercentage===0));});
test('health and active normalized catalogue are public while pilots remain private',async()=>{const f=await fixture();try{assert.equal((await fetch(`${f.base}/healthz`)).status,200);const data=await (await fetch(`${f.base}/v1/catalog/games`)).json();assert.equal(data.games.length,42);assert.ok(data.games.every(game=>game.gameUrl.startsWith('https://')));for(const pilot of pilotCatalogue)assert.equal(data.games.some(game=>game.id===pilot.id),false);}finally{await f.close();}});
test('OTP creates a secure, enumeration-safe session',async()=>{const f=await fixture();try{const auth=await signIn(f.base);const response=await fetch(`${f.base}/v1/session`,{headers:{cookie:auth.cookie}});const session=await response.json();assert.equal(session.authenticated,true);assert.equal(session.entitlement.tier,'free');assert.equal(session.sessions.length,1);assert.equal(f.store.otp.values().next().value.code,undefined);}finally{await f.close();}});
test('state changes require CSRF',async()=>{const f=await fixture();try{const auth=await signIn(f.base);const response=await fetch(`${f.base}/v1/play-sessions`,{method:'POST',headers:{cookie:auth.cookie,'content-type':'application/json'},body:JSON.stringify({gameId:f.store.games.find(item=>item.tier==='free').id})});assert.equal(response.status,403);assert.equal((await response.json()).error.code,'csrf_failed');}finally{await f.close();}});
test('rewards require exact nonce and game version and remain idempotent',async()=>{const f=await fixture();try{const auth=await signIn(f.base);const game=f.store.games.find(item=>item.tier==='free');let response=await fetch(`${f.base}/v1/play-sessions`,{method:'POST',headers:headers(auth),body:JSON.stringify({gameId:game.id})});const play=await response.json();f.advance(45000);response=await fetch(`${f.base}/v1/play-sessions/${play.playSessionId}/complete`,{method:'POST',headers:headers(auth),body:JSON.stringify({score:500,durationMs:45000,completedAt:Date.now(),gameVersion:play.gameVersion})});assert.equal(response.status,422);response=await fetch(`${f.base}/v1/play-sessions/${play.playSessionId}/complete`,{method:'POST',headers:headers(auth),body:JSON.stringify({score:500,durationMs:45000,completedAt:Date.now(),gameVersion:'wrong',nonce:play.nonce})});assert.equal(response.status,422);response=await fetch(`${f.base}/v1/play-sessions/${play.playSessionId}/complete`,{method:'POST',headers:headers(auth),body:JSON.stringify({score:500,durationMs:45000,completedAt:Date.now(),gameVersion:play.gameVersion,nonce:play.nonce})});const first=await response.json();assert.equal(response.status,200);assert.equal(first.reward,game.reward);response=await fetch(`${f.base}/v1/play-sessions/${play.playSessionId}/complete`,{method:'POST',headers:headers(auth),body:JSON.stringify({score:999,durationMs:50000,gameVersion:play.gameVersion,nonce:play.nonce})});const second=await response.json();assert.equal(second.balance,game.reward);assert.equal(second.idempotent,true);}finally{await f.close();}});
test('browser payment return never activates entitlement',async()=>{const f=await fixture();try{const auth=await signIn(f.base);let response=await fetch(`${f.base}/v1/payments/jazzcash/checkout`,{method:'POST',headers:{...headers(auth),'idempotency-key':'checkout-return'},body:JSON.stringify({planId:'monthly'})});const checkout=await response.json();const payload=JSON.stringify(paidPayload(checkout.transactionId));response=await fetch(`${f.base}/v1/payments/jazzcash/return`,{method:'POST',redirect:'manual',headers:{'content-type':'application/json','x-jazzcash-signature':hmac('test-secret',payload)},body:payload});assert.equal(response.status,303);const entitlement=await (await fetch(`${f.base}/v1/entitlements/me`,{headers:{cookie:auth.cookie}})).json();assert.equal(entitlement.entitlement,'free');}finally{await f.close();}});
test('verified payment event validates stored values and activates once',async()=>{const f=await fixture();try{const auth=await signIn(f.base);let response=await fetch(`${f.base}/v1/payments/jazzcash/checkout`,{method:'POST',headers:{...headers(auth),'idempotency-key':'checkout-1'},body:JSON.stringify({planId:'monthly'})});const checkout=await response.json();assert.equal(response.status,201);let mismatch={...paidPayload(checkout.transactionId),providerEventId:'bad-amount',amountMinor:1};let payload=JSON.stringify(mismatch);response=await fetch(`${f.base}/v1/payments/jazzcash/webhook`,{method:'POST',headers:{'content-type':'application/json','x-jazzcash-signature':hmac('test-secret',payload)},body:payload});assert.equal(response.status,422);let entitlement=await (await fetch(`${f.base}/v1/entitlements/me`,{headers:{cookie:auth.cookie}})).json();assert.equal(entitlement.entitlement,'free');const paid=paidPayload(checkout.transactionId);payload=JSON.stringify(paid);response=await fetch(`${f.base}/v1/payments/jazzcash/webhook`,{method:'POST',headers:{'content-type':'application/json','x-jazzcash-signature':hmac('test-secret',payload)},body:payload});assert.equal(response.status,202);entitlement=await (await fetch(`${f.base}/v1/entitlements/me`,{headers:{cookie:auth.cookie}})).json();assert.equal(entitlement.entitlement,'premium');response=await fetch(`${f.base}/v1/payments/jazzcash/webhook`,{method:'POST',headers:{'content-type':'application/json','x-jazzcash-signature':hmac('test-secret',payload)},body:payload});assert.equal((await response.json()).duplicate,true);}finally{await f.close();}});
test('idempotency is scoped to the authenticated purchase',async()=>{const f=await fixture();try{const first=await signIn(f.base,'03001234567');const second=await signIn(f.base,'03007654321');const create=auth=>fetch(`${f.base}/v1/payments/jazzcash/checkout`,{method:'POST',headers:{...headers(auth),'idempotency-key':'same-browser-key'},body:JSON.stringify({planId:'monthly'})});const a=await (await create(first)).json();const b=await (await create(second)).json();assert.notEqual(a.transactionId,b.transactionId);}finally{await f.close();}});
test('account export, logout-all and deletion are available',async()=>{const f=await fixture();try{const auth=await signIn(f.base);let response=await fetch(`${f.base}/v1/account/export`,{headers:{cookie:auth.cookie}});const exported=await response.json();assert.equal(exported.user.id,auth.user.id);response=await fetch(`${f.base}/v1/auth/logout-all`,{method:'POST',headers:headers(auth)});assert.equal(response.status,200);response=await fetch(`${f.base}/v1/account`,{method:'DELETE',headers:headers(auth)});assert.equal(response.status,202);}finally{await f.close();}});
test('administrator roles come from the authenticated identity',async()=>{const f=await fixture();try{let response=await fetch(`${f.base}/v1/admin/metrics`,{headers:{'x-admin-key':'finance-key-1234567890','x-admin-role':'security'}});assert.equal(response.status,403);response=await fetch(`${f.base}/v1/admin/payments`,{headers:{'x-admin-key':'finance-key-1234567890','x-admin-role':'security'}});assert.equal(response.status,200);response=await fetch(`${f.base}/v1/admin/metrics`,{headers:{'x-admin-key':'security-key-123456789','x-admin-role':'finance'}});assert.equal(response.status,200);}finally{await f.close();}});
