import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {createApp} from '../src/app.mjs';
import {loadConfig} from '../src/config.mjs';
import {MemoryStore} from '../src/adapters/memory-store.mjs';
import {JazzCashAdapter} from '../src/adapters/jazzcash.mjs';
import {hmac} from '../src/lib/security.mjs';
import {catalogue,quarantinedCatalogue} from '../src/catalogue/index.mjs';

async function fixture(){let now=Date.now();const clock=()=>now;const config=loadConfig({nodeEnv:'test',port:1,publicOrigin:'http://localhost',allowedOrigins:['http://localhost'],allowDebugOtp:true,jazzcashMode:'mock',jazzcashWebhookSecret:'test-secret',adminApiKeys:['admin-key'],rewardDailyCap:1000});const store=new MemoryStore();const jazzcash=new JazzCashAdapter(config);const server=createServer(createApp({config,store,jazzcash,clock}));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));return{base:`http://127.0.0.1:${server.address().port}`,store,advance(ms){now+=ms;},close:()=>new Promise(resolve=>server.close(resolve))};}
async function signIn(base,identifier='03001234567'){let response=await fetch(`${base}/v1/auth/otp`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identifier})});const challenge=await response.json();assert.equal(response.status,202);response=await fetch(`${base}/v1/auth/otp/verify`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({challengeId:challenge.challengeId,code:challenge.debugCode})});const body=await response.json();assert.equal(response.status,200);const setCookies=response.headers.getSetCookie?.()??[response.headers.get('set-cookie')];const values={};for(const line of setCookies.filter(Boolean))for(const part of line.split(/,(?=\s*[^;,]+=)/)){const pair=part.trim().split(';')[0];const index=pair.indexOf('=');values[pair.slice(0,index)]=pair.slice(index+1);}return{cookie:Object.entries(values).map(([key,value])=>`${key}=${value}`).join('; '),csrf:body.csrfToken,user:body.user};}
const headers=auth=>({'content-type':'application/json',cookie:auth.cookie,'x-csrf-token':auth.csrf,origin:'http://localhost'});

test('catalogue import separates live and quarantined games',()=>{assert.equal(catalogue.length,44);assert.equal(quarantinedCatalogue.length,17);assert.ok(catalogue.every(game=>game.status==='live'&&game.gameUrl.startsWith('https://')));});
test('health and normalized catalogue are public',async()=>{const f=await fixture();try{assert.equal((await fetch(`${f.base}/healthz`)).status,200);const data=await (await fetch(`${f.base}/v1/catalog/games`)).json();assert.equal(data.games.length,44);assert.ok(data.games.every(game=>game.gameUrl.startsWith('https://')));}finally{await f.close();}});
test('OTP creates a secure, enumeration-safe session',async()=>{const f=await fixture();try{const auth=await signIn(f.base);const response=await fetch(`${f.base}/v1/session`,{headers:{cookie:auth.cookie}});const session=await response.json();assert.equal(session.authenticated,true);assert.equal(session.entitlement.tier,'free');assert.equal(session.sessions.length,1);assert.equal(f.store.otp.values().next().value.code,undefined);}finally{await f.close();}});
test('state changes require CSRF',async()=>{const f=await fixture();try{const auth=await signIn(f.base);const response=await fetch(`${f.base}/v1/play-sessions`,{method:'POST',headers:{cookie:auth.cookie,'content-type':'application/json'},body:JSON.stringify({gameId:f.store.games.find(item=>item.tier==='free').id})});assert.equal(response.status,403);assert.equal((await response.json()).error.code,'csrf_failed');}finally{await f.close();}});
test('rewards are server-authoritative, plausible and idempotent',async()=>{const f=await fixture();try{const auth=await signIn(f.base);const game=f.store.games.find(item=>item.tier==='free');let response=await fetch(`${f.base}/v1/play-sessions`,{method:'POST',headers:headers(auth),body:JSON.stringify({gameId:game.id})});const play=await response.json();f.advance(45000);response=await fetch(`${f.base}/v1/play-sessions/${play.playSessionId}/complete`,{method:'POST',headers:headers(auth),body:JSON.stringify({score:500,durationMs:45000,completedAt:Date.now(),gameVersion:play.gameVersion,nonce:play.nonce})});const first=await response.json();assert.equal(response.status,200);assert.equal(first.reward,game.reward);response=await fetch(`${f.base}/v1/play-sessions/${play.playSessionId}/complete`,{method:'POST',headers:headers(auth),body:JSON.stringify({score:999,durationMs:50000,nonce:play.nonce})});const second=await response.json();assert.equal(second.balance,game.reward);assert.equal(second.idempotent,true);}finally{await f.close();}});
test('verified payment event activates entitlement once',async()=>{const f=await fixture();try{const auth=await signIn(f.base);let response=await fetch(`${f.base}/v1/payments/jazzcash/checkout`,{method:'POST',headers:{...headers(auth),'idempotency-key':'checkout-1'},body:JSON.stringify({planId:'monthly'})});const checkout=await response.json();assert.equal(response.status,201);let entitlement=await (await fetch(`${f.base}/v1/entitlements/me`,{headers:{cookie:auth.cookie}})).json();assert.equal(entitlement.entitlement,'free');const payload=JSON.stringify({transactionId:checkout.transactionId,status:'paid',providerReference:'JC-PAID',providerEventId:'event-1'});response=await fetch(`${f.base}/v1/payments/jazzcash/webhook`,{method:'POST',headers:{'content-type':'application/json','x-jazzcash-signature':hmac('test-secret',payload)},body:payload});assert.equal(response.status,202);entitlement=await (await fetch(`${f.base}/v1/entitlements/me`,{headers:{cookie:auth.cookie}})).json();assert.equal(entitlement.entitlement,'premium');response=await fetch(`${f.base}/v1/payments/jazzcash/webhook`,{method:'POST',headers:{'content-type':'application/json','x-jazzcash-signature':hmac('test-secret',payload)},body:payload});assert.equal((await response.json()).duplicate,true);}finally{await f.close();}});
test('account export, logout-all and deletion are available',async()=>{const f=await fixture();try{const auth=await signIn(f.base);let response=await fetch(`${f.base}/v1/account/export`,{headers:{cookie:auth.cookie}});const exported=await response.json();assert.equal(exported.user.id,auth.user.id);response=await fetch(`${f.base}/v1/auth/logout-all`,{method:'POST',headers:headers(auth)});assert.equal(response.status,200);response=await fetch(`${f.base}/v1/account`,{method:'DELETE',headers:headers(auth)});assert.equal(response.status,202);}finally{await f.close();}});
test('admin endpoints require a key and expose operations data',async()=>{const f=await fixture();try{assert.equal((await fetch(`${f.base}/v1/admin/metrics`)).status,401);const response=await fetch(`${f.base}/v1/admin/metrics`,{headers:{'x-admin-key':'admin-key','x-admin-role':'security'}});assert.equal(response.status,200);assert.ok((await response.json()).counters);}finally{await f.close();}});
