import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {createApp} from '../src/app.mjs';
import {createMvpApp} from '../src/mvp-app.mjs';
import {loadConfig} from '../src/config.mjs';
import {MemoryStore} from '../src/adapters/memory-store.mjs';
import {JazzCashAdapter} from '../src/adapters/jazzcash.mjs';
import {PaymentService} from '../src/services/payments.mjs';
async function fixture(){const config=loadConfig({nodeEnv:'test',port:1,publicOrigin:'http://localhost',allowedOrigins:['http://localhost'],allowDebugOtp:true,jazzcashMode:'mock',jazzcashWebhookSecret:'test-secret',topupOffers:[{id:'starter',label:'Starter',coins:100,amountPkr:99,status:'live'}],voucherCodes:{ARENA100:100},supportRateLimit:5});const store=new MemoryStore();const jazzcash=new JazzCashAdapter(config);const payments=new PaymentService({store,provider:jazzcash});const supportDelivery={send:async()=>({delivered:false,provider:'disabled'})};const mvp=createMvpApp({config,store,payments,supportDelivery});const primary=createApp({config,store,jazzcash,payments});const server=createServer(async(req,res)=>{if(await mvp(req,res)!==false)return;await primary(req,res);});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));return{base:`http://127.0.0.1:${server.address().port}`,store,close:()=>new Promise(resolve=>server.close(resolve))};}
async function signIn(base,identifier='03001234567'){let response=await fetch(`${base}/v1/auth/otp`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identifier})});const challenge=await response.json();response=await fetch(`${base}/v1/auth/otp/verify`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({challengeId:challenge.challengeId,code:challenge.debugCode})});const body=await response.json();const setCookies=response.headers.getSetCookie?.()??[response.headers.get('set-cookie')];const values={};for(const line of setCookies.filter(Boolean))for(const part of line.split(/,(?=\s*[^;,]+=)/)){const pair=part.trim().split(';')[0];const index=pair.indexOf('=');values[pair.slice(0,index)]=pair.slice(index+1);}return{cookie:Object.entries(values).map(([key,value])=>`${key}=${value}`).join('; '),csrf:body.csrfToken,user:body.user};}
const headers=auth=>({'content-type':'application/json',cookie:auth.cookie,'x-csrf-token':auth.csrf,origin:'http://localhost'});
test('top-up offers and checkout are configurable',async()=>{const f=await fixture();try{let response=await fetch(`${f.base}/v1/offers/topups`);assert.equal((await response.json()).offers.length,1);const auth=await signIn(f.base);response=await fetch(`${f.base}/v1/offers/topups/checkout`,{method:'POST',headers:headers(auth),body:JSON.stringify({offerId:'starter'})});const body=await response.json();assert.equal(response.status,201);assert.equal(body.coins,100);}finally{await f.close();}});
test('voucher redemption is idempotent per account',async()=>{const f=await fixture();try{const auth=await signIn(f.base);let response=await fetch(`${f.base}/v1/vouchers/redeem`,{method:'POST',headers:headers(auth),body:JSON.stringify({code:'ARENA100'})});let body=await response.json();assert.equal(response.status,201);assert.equal(body.balance,100);response=await fetch(`${f.base}/v1/vouchers/redeem`,{method:'POST',headers:headers(auth),body:JSON.stringify({code:'ARENA100'})});body=await response.json();assert.equal(body.duplicate,true);assert.equal(body.balance,100);}finally{await f.close();}});
test('multiplayer room and support ticket flows work',async()=>{const f=await fixture();try{const auth=await signIn(f.base);const game=f.store.games.find(item=>item.multiplayer);assert.ok(game);let response=await fetch(`${f.base}/v1/multiplayer/rooms`,{method:'POST',headers:headers(auth),body:JSON.stringify({gameId:game.id,name:'Test Room',maxPlayers:2})});await response.json();assert.equal(response.status,201);response=await fetch(`${f.base}/v1/multiplayer/rooms`);assert.equal((await response.json()).rooms.length,1);response=await fetch(`${f.base}/v1/support/tickets`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({topic:'Game not loading',message:'The game stops on the loading screen.'})});assert.equal(response.status,201);assert.ok((await response.json()).ticket.id.startsWith('GA-'));}finally{await f.close();}});
