import test from 'node:test';
import assert from 'node:assert/strict';
import {loadConfig} from '../src/config.mjs';
import {authenticateAdmin,signAdminAssertion} from '../src/lib/admin-auth.mjs';
import {MemoryStore} from '../src/adapters/memory-store.mjs';
import {SupportDelivery} from '../src/adapters/support-delivery.mjs';
import {processAccountRetention} from '../src/services/account-retention.mjs';

const request=headers=>({headers});
const signingMaterial=label=>`${label}-${'x'.repeat(32)}`;

test('signed administrator assertions bind identity to configured roles',()=>{const material=signingMaterial('administrator');const issuedAt=Date.now();const identity='finance@example.com';const roles=['finance'];const config=loadConfig({nodeEnv:'production',databaseUrl:'postgres://example',adminAuthMode:'signed-headers',adminPrincipals:[],adminProxySecret:material,adminIdentityRoles:{[identity]:roles}});const signature=signAdminAssertion({identity,roles,issuedAt,secret:material});const principal=authenticateAdmin(request({'x-admin-identity':identity,'x-admin-roles':'finance','x-admin-issued-at':String(issuedAt),'x-admin-signature':signature}),config,['finance']);assert.equal(principal.role,'finance');assert.throws(()=>authenticateAdmin(request({'x-admin-identity':identity,'x-admin-roles':'admin','x-admin-issued-at':String(issuedAt),'x-admin-signature':signAdminAssertion({identity,roles:['admin'],issuedAt,secret:material})}),config,['admin']),error=>error.code==='admin_forbidden');});

test('support delivery signs the exact payload and rejects insecure endpoints',async()=>{let observed;const material=signingMaterial('support');const delivery=new SupportDelivery({mode:'http',endpoint:'https://support.example.test/tickets',secret:material,fetchImpl:async(url,options)=>{observed={url:String(url),options};return new Response(null,{status:202});}});const result=await delivery.send({id:'GA-123',userId:'user-1',topic:'Loading',message:'The game does not load.',reference:'game-1',createdAt:'2026-07-31T00:00:00.000Z'});assert.equal(result.delivered,true);assert.equal(observed.url,'https://support.example.test/tickets');assert.match(observed.options.headers['x-game-arena-signature'],/^[a-f0-9]{64}$/);const insecure=new SupportDelivery({mode:'http',endpoint:'http://support.example.test',secret:material});await assert.rejects(()=>insecure.send({id:'GA-1'}),error=>error.code==='support_delivery_unavailable');});

test('retention deletes expired accounts but preserves legal holds',()=>{const store=new MemoryStore();const expired=store.findOrCreateUser({type:'phone',value:'+923001111111'});const held=store.findOrCreateUser({type:'phone',value:'+923002222222'});const now=Date.UTC(2026,6,31);store.requestDeletion(expired.id,now-31*86400000);store.requestDeletion(held.id,now-31*86400000);store.createSupportTicket({userId:expired.id,topic:'Privacy',message:'Please remove this account and its support content.',reference:'account'});const result=processAccountRetention(store,{now,retentionDays:30,legalHoldUserIds:[held.id]});assert.equal(result.processed,1);assert.equal(store.users.get(expired.id).status,'deleted');assert.equal(store.getUser(expired.id),null);assert.equal([...store.identities.values()].some(item=>item.userId===expired.id),false);assert.equal(store.supportTickets[0].message,'[deleted by account retention policy]');assert.equal(store.users.get(held.id).status,'deletion_pending');});
